### ISSUE TITLE
zerop: Searching for program: no such file or directory, diff

### ISSUE THREAD

**Issue by shuweicn** [dominikh/go-mode.el#105]
Dear

Gofmt don't know why this is so.

I only installed the go-code,no other plugin.my system is windows 10.other computers do not have this proble,same system an config.

Fllowing error code.

Wrote c:/Users/hehe/AppData/Local/Temp/gofmt8616ORj.go
zerop: Searching for program: no such file or directory, diff

**Comment by dominikh** [comment]
Using gofmt in go-mode requires the `diff` programm to be installed and in PATH. If it works on your other systems and not this one, then this one is apparently missing `diff`.

**Comment by shuweicn** [comment]
Thank you.
