### ISSUE TITLE
error in before-save-hook?

### ISSUE THREAD

**Issue by stevenbenjamin** [dominikh/go-mode.el#106]
Not sure if this is a bug in go-mode or something in my configuration. I suspect my configuration only because I don't see any instances of this reported. gofmt on the save hook was working on a previous version. 

Running into the following on save:

Error: (wrong-number-of-arguments #[(arg) "\212p\306\211\307\303!\203\310 \210\311\306\312\"\210\313 \203#\314\315!\210\202X\316 \211\306\211\203Q
@\317!\210\320 \210\203G\321\322 \323 \"\210\202J\324 \210
A\211\204.*\314\325G\"\210	\205^\326 ,\207" [lines flymake-state cur-buffer flymake-mode import --dolist-tail-- nil boundp flymake-mode-off save-some-buffers #[nil "p\232\207" [cur-buffer] 2] buffer-modified-p message "Cannot operate on unsaved buffer" go-unused-imports-lines go--goto-line beginning-of-line comment-region line-beginning-position line-end-position go--delete-whole-line "Removed %d imports" flymake-mode-on arg] 4 ("/Users/me/Library/Preferences/Aquamacs Emacs/Packages/elpa/go-mode-20150817.2318/go-mode.elc" . 43046) "P"] 0)

 This is configured in .emacs with :

(add-hook 'before-save-hook 'gofmt-before-save)
(add-hook 'before-save-hook 'go-remove-unused-imports)

**Comment by dominikh** [comment]
Before I address the actual issue: Please note that running go-remove-unused-imports in a before-save-hook does not work. The function depends on the buffer being unmodified, which isn't the case in a before-save hook. The function will thus do nothing

Now to the issue: It is a configuration issue. The error stems from the fact that go-remove-unused-imports requires an argument. 

Also be aware that, unless you add these hooks only to Go buffers, they will cause you further problems. gofmt-before-save is designed in a way that it will do nothing if saving a non-Go buffer, which makes it safe to use as a global hook. go-remove-unused-imports, however, isn't. It will happily try to operate on any file you save.

On a final note, I suggest you take a look at goimports – it's a drop-in replacement for gofmt that in addition to formatting source code also adds missing imports and removes unused ones.

Closing this issue as it is a configuration error.

**Comment by stevenbenjamin** [comment]
Dominikh, 
Thanks for the response and the clarification.  Much appreciated.

Steve Benjamin
