### ISSUE TITLE
weird message in my emacs when I try load go-mode

### ISSUE THREAD

**Issue by cocodrino** [dominikh/go-mode.el#107]
Hi, sorry but I don't have so much experience debugging emacs, when I've installed go-mode using melpa but when I try run it I get 

```emacs
sort: Wrong type argument: number-or-marker-p, #[257 "ÀÁDÂDE" [and symbolp cl--find-class] 5 "

(fn NAME)"]
sort: Wrong type argument: number-or-marker-p, #[257 "ÀÁDÂDE" [and symbolp cl--find-class] 5 "

(fn NAME)"]
user-error: Minibuffer window is not active
```

I've tried doing the manual installation but the problem persist, please let me know if you need more info
emacs 

emacs GNU Emacs 25.0.50.2 
elementary linux 
go-mode from melpa-stable and marmalade 

thanks.

**Comment by dominikh** [comment]
Please set `debug-on-error` to `t` and provide an actual backtrace of the issue.

**Comment by dominikh** [comment]
Closing due to lack of feedback.

**Comment by cocodrino** [comment]
sorry @dominikh , I'd fix the issue after update my emacs packages, now it works perfect, sorry for don't asnwer before, thank you

**Comment by TeMPOraL** [comment]
Curiously, I get the same error message while *compiling the Emacs from sources*.
