### ISSUE TITLE
godoc can't find doc on import

### ISSUE THREAD

**Issue by stardiviner** [dominikh/go-mode.el#108]
I try to query `godoc` on keywords like: `package` or `import`.
And output error is:
```
  doc: no buildable Go source files in /home/stardiviner
  exit status 1
```
(This is the out put from command `go doc import`)
And another command `godoc import` output is:
```
2015/11/24 11:56:55 open /usr/lib/go/src/package: no such file or directory
```

I don't know whether Go doc don't have this doc by default.
So ask here.

**Comment by dominikh** [comment]
> I don't know whether Go doc don't have this doc by default.

So run the commands on a command line and see?

Neither `godoc package` nor `go doc package` are valid invocations.
