### ISSUE TITLE
Forward-word and backword-word skips over entire backquoted strings - should stop at each word in the string

### ISSUE THREAD

**Issue by ericpromislow** [dominikh/go-mode.el#111]
This happens when I start emacs with the -q option to skip my customizations, and then load only go-mode.el. I've tried commenting out the syntax-entry for ?`, and that had no effect, so something else is going on.

**Comment by dominikh** [comment]
I cannot reproduce this with GNU Emacs 24.5.1 -- which version of Emacs, and which version of go-mode, are you using?

Also, can you provide a complete file that reproduces the issue on your end?

**Comment by ericpromislow** [comment]
Go mode 1.3.1,  emacs 23.4, complete file:

    package main
    
    import (
    	"fmt"
    )
    
    func main() {
    	a := `line 1
    line 2
    line 3
    line 4`
    	fmt.Println(a)
    }
    
Repro: put the cursor to between "line" and "1" at the start of the assignment
and do forward-word ==> the cursor I mean "mark" moves to the end of the
backquoted string.

This doesn't happen in emacs 24.3, but I find it unusable because they
broke the way \C-y works in an isearch.  Now I'm doing a find from / looking
for isearch.el, because all I could find in /usr/share was isearch.elc

Wondering if you can tell me where the file is before find finishes :)

**Comment by ericpromislow** [comment]
Forget it.  I worked out how to rebind isearch-yank-line in an isearch-mode-hook when the
major version >= 24. So I'll finally wave good bye to emacs 23.
