### ISSUE TITLE
Source buffer should be read-only when godef jumped into it

### ISSUE THREAD

**Issue by douglarek** [dominikh/go-mode.el#114]

**Comment by dominikh** [comment]
Why?

**Comment by douglarek** [comment]
If the source is golang std library，would you wish it by mistake ？

**Comment by dominikh** [comment]
Actually, as someone who works on the Go standard library from time to time, I rely on the current behaviour.

If you don't want to edit files in the standard library, don't make them writeable (`chmod -R ugo-w $(go env GOROOT)/src`) or write an elisp advise to modify the behaviour of godef-jump.

godef-jump is just a Go-specific variant of find-tag. The intention of both is to navigate code, and code is usually navigated to be worked on.
