### ISSUE TITLE
go-packages doesn't work on Cygwin

### ISSUE THREAD

**Issue by juergenhoetzel** [dominikh/go-mode.el#121]
Hi Dominik,

I also had issues on Cygwin using the _go-import-add_ functionality. _go-packages_ just returns _nil_ on Cygwin, because of the native Windows Paths:

```
ELISP> (go-packages)
nil
```

Also see:
https://github.com/dominikh/go-mode.el/pull/120#issuecomment-180791992

**Comment by dominikh** [comment]
> because of the native Windows Paths

Can you expand? If Emacs and Go both run inside Cygwin, `go-root-and-paths` should return valid paths that `go-packages` can look for packages in. If Emacs runs in Cygwin but Go doesn't, I'd still expect valid paths. The only constellation that could cause problems would be native Emacs and Go in cygwin, but there's no reason for running such a setup.

So, what is the value returned by `go-root-and-paths`?

**Comment by juergenhoetzel** [comment]
Actually, there is no _Go_ Cygwin package. I use the official build.

```
ELISP> (go-root-and-paths)
("C:\\Go" "c" "/cygwin64/home/juergen/go")
```

**Comment by dominikh** [comment]
What's the output of `go env GOROOT GOPATH`? I don't quite understand where that `"c"` is coming from. Also, what's the value of `path-separator` in Emacs?

**Comment by juergenhoetzel** [comment]
@dominikh  Hi,

```
go env GOROOT GOPATH
C:\Go
c:/cygwin64/home/juergen/go
```

```
ELISP> path-separator
":"
```
This is the Cygwin path-seperator, not the native. 

So the "c" is there because of this split:

`(paths (split-string (cadr output) path-separator))`

Anyway, the root cause of the problem is that, the paths need to be translated via _cygpath_, from ntative to Cygwin.

**Comment by dominikh** [comment]
I guess "patches welcome". I do not develop on Windows, and I'm not a fan of Cygwin. If there's a way to detect automatically that we're running in Cygwin and need to transform paths, let's add that.

How do other Emacs packages deal with this?

**Comment by juergenhoetzel** [comment]
This is what I used for Cygwin support in  Cider:

https://github.com/clojure-emacs/cider/pull/506

Well but  this would make the current solution even more complicated. My proposal is just to use a ```defcustom``` because generic filename translation is not required.

**Comment by dominikh** [comment]
Do we need to do anything further for Cygwin support, or is using `go list` in go-packages enough?

**Comment by juergenhoetzel** [comment]
LGTM
