### ISSUE TITLE
Warning: cl package required at runtime

### ISSUE THREAD

**Issue by tleyden** [dominikh/go-mode.el#122]
I installed go-mode via the melpa bleeding edge repo and got these warnings:

```
Compiling file /Users/tleyden/.emacs.d/elpa/go-mode-20160127.4/go-mode.el at Sat Feb  6 17:58:11 2016
Entering directory `/Users/tleyden/.emacs.d/elpa/go-mode-20160127.4/'
go-mode.el:16:1:Warning: cl package required at runtime

In go-mode:
go-mode.el:917:10:Warning: `font-lock-syntactic-keywords' is an obsolete
    variable (as of 24.1); use `syntax-propertize-function' instead.
```

I'm using [emacsformacosx](emacsformacosx.com) v 24.5 (9.0) on OSX El Capitan 

My `~/.emacs.d/init.el` file:

```
(require 'package)
(add-to-list 'package-archives
  '("melpa" . "http://melpa.milkbox.net/packages/") t)
```

**Comment by tleyden** [comment]
Nevermind, looks like these warnings can be ignored.

> Warning: cl package required at runtime

http://stackoverflow.com/questions/5019724/in-emacs-what-does-this-error-mean-warning-cl-package-required-at-runtime

> go-mode.el:917:10:Warning: `font-lock-syntactic-keywords' is an obsolete

Looks like that's a known warning that can be ignored?

https://github.com/dominikh/go-mode.el/pull/95

**Comment by dominikh** [comment]
Re cl: Yes, we use cl. We're not GNU, we actually like cl, the warning can be ignored.

Re font-lock-syntactic-keywords: If there's some trick to tell the compiler that we're only using it with older versions of Emacs, please let me know. 

Either way, all of these warnings are harmless.

**Comment by dominikh** [comment]
bdf353a5992ce493d6f6510f442384cdae155e58 and 7c5e9ade4cf6036eb1eda8cc588b390927321f6e address this issue.
