### ISSUE TITLE
Use a different prefix key for go-goto-map

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-mode.el#125]
We shouldn't use `C-c C-g` as that overrides the original meaning of `C-g`: quit. We can't use `C-c C-j` either, as that's already in use by `godef-jump`. What other key could we use?

/cc @thiderman

**Comment by thiderman** [comment]
Hm, tricky. I personally am using `C-c g` since I feel that's slightly easier to type, but that's also against the conventions. `C-c C-m` as in "move" or `C-c C-f` since these are all function related gotos?

**Comment by dominikh** [comment]
> since these are all function related gotos

`go-goto-imports` isn't function-related. And `C-c C-m` is awkward because `C-m` is identical to `RET`. :-(

**Comment by thiderman** [comment]
Haha, this makes it trickier. :')

I really want them to be bound to something by default. Maybe we can remove the `go-goto-imports` from this group and still use `C-c C-f`?

**Comment by dominikh** [comment]
I'll use `C-c C-f` and pretend that it stands for `find`... Emacs keybindings aren't supposed to make sense, are they?
