### ISSUE TITLE
lastest commit requires new version of goimports.

### ISSUE THREAD

**Issue by newhook** [dominikh/go-mode.el#126]
I was a bit suprised when after updating last night go-mode in spacemacs suddenly started failing with an error from gofmt. Looking at the messages I saw:

```
Calling gofmt: goimports (-srcdir /Users/matthew/src/services/src/chgbuf/ -w /var/folders/hg/np4sqzds1h58hql8337fvn0r0000gn/T/gofmt4232TJr.go)
```

After digging around for a bit I saw that https://github.com/dominikh/go-mode.el/commit/8d1594fa56823300d36a45c3a483de3f0d503ff2 started magically detecting go-imports and adding the -srcdir arg which wasn't supported by older versions of go-imports. Updating go-imports fixed the issue, but it would have been a less frustrating experience if somehow I was warned that updating go-imports was required.

**Comment by dominikh** [comment]
Do you have a suggestion for how we should warn/inform users?

**Comment by newhook** [comment]
Pop a dialog? I'm not that familiar with emacs internals so I don't know how practical that is. Another suggestion would be to not use this argument on a version of go-imports which does not support it.

**Comment by dominikh** [comment]
Well, getting an error is your "dialog". We could theoretically detect the error output and re-run without the srcdir flag, but I'm not sure it is worth the extra complexity. I'd much rather people updated to the latest goimports. They really should, as they may end up with incorrect imports as soon as they work with vendoring if they don't update.

**Comment by newhook** [comment]
Perhaps the problem is mine, but I found it confusing to suddenly have saving files pop an error about -srcdir being an invalid argument especially when I didn't really remember updating last night before going to bed :)

**Comment by dominikh** [comment]
I'll see if I can emit a nicer error when we detect goimports complaining about the flag.

**Comment by dominikh** [comment]
We'll now print `Your version of goimports is too old and doesn't support vendoring. Please update goimports!` at the top of the gofmt error buffer if we detect that the error was due to `-srcdir` being unsupported. This should be good enough I think.

**Comment by newhook** [comment]
Sounds great!
