### ISSUE TITLE
Switching from "godoc" to "go doc"

### ISSUE THREAD

**Issue by iced** [dominikh/go-mode.el#127]
godoc: doc: import "/usr/local/Cellar/go/1.6/libexec/src/fmt/": cannot import absolute path

>the value of godoc-command (if the variable exists)
godoc-command is a variable defined in `go-mode.el'.
Its value is "go doc"

>the exact command and input you used
godoc-at-point on fmt.Sprintf (same for all funcs)

>the output of go env GOROOT and ls $(go env GOROOT) in a shell
iced@icedm: ~ $ go env GOROOT
/usr/local/Cellar/go/1.6/libexec
iced@icedm: ~ $ ls $(go env GOROOT)
CONTRIBUTING.md  CONTRIBUTORS     PATENTS          VERSION          api/             bin/             doc/             favicon.ico      lib/             misc/            pkg/             robots.txt       src/             test/

**Comment by 7sharp9** [comment]
I get similar on using go-doc-at-point on Printf for example:
```
fmt.Printf("hello, world\n")
```

>godoc: doc: import "/usr/local/go/src/fmt/": cannot import absolute path
exit status 1
