### ISSUE TITLE
Wrong file names with goimports

### ISSUE THREAD

**Issue by iced** [dominikh/go-mode.el#129]
When I `(setq gofmt-command "goimports")`, errors display isn't that useful as with `"gofmt"` as you get temporary files names like:

```
gofmt errors:
/Users/iced/dev/test/gofmt43340N9P.go:37:42: expected '{', found newline
```

Manually jumping to specific line isn't that convenient as M-g M-n.

Behavior with gofmt is correct:

```
gofmt errors:
test.go:37:23: expected '{', found newline
```

**Comment by dominikh** [comment]
I can't quite reproduce the issue locally, nor yet understand why it's happening. gofmt and goimports output pass through the exact same filter that replaces the temporary file name with the actual file name.

**Comment by iced** [comment]
Debugged abit.

gomft receives following args:

```
(filename /Users/iced/dev/test/test.go)
(tmpfile /var/folders/np/ft_20hn570s7dlq5n6wnhsfw0000gn/T/gofmt43340B0Q.go)
```

While in `*Gofmt Errors*` I got paths starting with `/Users/iced/dev/test`. Can you try to get latest goimports and check with it?

**Comment by dominikh** [comment]
Thanks. This is https://github.com/golang/go/issues/14864. I'll wait and see if upstream agrees with me that it's a bug or not.

**Comment by iced** [comment]
I'd make this logic way simpler - just replace everything till last `:` by file name (which is known).

Also I haven't looked deeper, but why you need temp file at all? Emacs got perfect undo mechanism...

**Comment by dominikh** [comment]
1. Older versions of Emacs (23.x) do not record file reloads in the undo history
2. Reloading the file, when it changed, will not maintain your cursor in the correct position. By applying modifications to the buffer, we have a far higher chance of keeping the cursor in the same relative position.
3. The current implementation works for buffers that do not have a file attached (e.g. the scratch buffer).

I'll still wait for upstream before touching any code in go-mode.

**Comment by iced** [comment]
1. come on :)
2. just use bookmark - it'll work same good.
3. that one's valid and probably makes current approach better :(

**Comment by iced** [comment]
works as intended, thanks.
