### ISSUE TITLE
godef: no declaration found for fmt.Println

### ISSUE THREAD

**Issue by hjolin** [dominikh/go-mode.el#134]
On my machine, linux mint 64 bit Emacs-24.5, currently " M-x godef " can't find declarations in golang standard packages in $GOROOT, while it works for third party packages inside $GOPATH directory.  Should I set any variables inside Emacs or any possible mistakes I have made?

**Comment by dominikh** [comment]
What's the output of

- `M-: (getenv "GOROOT")`
- `M-: (go-root-and-paths)
- `go env` in a shell.

**Comment by hjolin** [comment]
(getenv "GOROOT" ) : /usr/local/go

(go-root-and-paths) : ("/usr/local/go" "/home/huangjian/gopath")

go env in a shell : 

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/huangjian/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by dominikh** [comment]
Just to make sure: The fmt package was being imported?

Run the following in a shell to check if godef is working outside of emacs: 

```
echo 'package foo; import "fmt"; func fn() { fmt.Println() }' | godef -i -o 45
```

Then insert that same code in an Emacs buffer and run `godef-describe` with point on the `Println` identifier.

**Comment by hjolin** [comment]
**huangjian@HJ-LinuxMint ~ $ echo 'package foo; import "fmt"; func fn() {fmt.Println() }' | godef -i -o 45
parseLocalPackage error: no more package files found
godef: no declaration found for fmt.Println**

it seems that godef doesn't work outside of Emacs, but it does work for third party packages, confusing.

**Comment by hjolin** [comment]
Is this a bug of godef? I don't think it is a wrong of go-mode.

**Comment by dominikh** [comment]
If godef doesn't work outside of go-mode, then it's either an issue with your environment or a bug in godef. One last question before I redirect you to [godef's issue tracker](https://github.com/rogpeppe/godef/issues)

What version of Go are you using? (`go version`) – I expect that godef needs at least version 1.4.

**Comment by hjolin** [comment]
**go version go1.6 linux/amd64**

I installed go built from source and place it at /usr/local/go.

**Comment by dominikh** [comment]
Then I'm afraid I can't help you. You will want to ask the godef developer for help. Closing this issue. Good luck!

**Comment by cmcginty** [comment]
I had the same issue, and I resolved it by reinstalling godef package.

   cd $GOPATH/src/github.com/rogpeppe/godef && go install
