### ISSUE TITLE
Can't insert import path from vendor directory with "goimports"

### ISSUE THREAD

**Issue by enzochiau** [dominikh/go-mode.el#136]
Just follow the article [here](https://blog.filippo.io/most-go-tools-now-work-with-go15vendorexperiment/) to test `goimports` 

With the last `goimports`, and the command line give the correct import path.

But inside Emacs (Emacs-25), when I save the `main.go` file, there's no import path added.

**Comment by dominikh** [comment]
Please paste the results of the following three commands:

- `M-: (gofmt--is-goimports-p)`
- `M-: gofmt-command`
- `M-: (file-name-base gofmt-command)`

**Comment by enzochiau** [comment]
- M-: (gofmt--is-goimports-p)

    t

- M-: gofmt-command

    "goimports"

- M: (file-name-base gofmt-command)

    "goimports"

**Comment by dominikh** [comment]
Can you provide an input file for which goimports doesn't add an import, as well as the values of

- `M-: (getenv "GOPATH")`
- `M-: (buffer-file-name)`

**Comment by enzochiau** [comment]
Because it has `vendor`, you can clone my test repo [here](https://github.com/enzochiau/go16vendor) to your go path. `go get` won't work because the missing `import` path. 

main.go

    package main
    
    import "fmt"
    
    func main() {
    	fmt.Println(hello.Hello)
    }

my `goimports main.go` output from terminal is

    package main
    
    import (
    	"fmt"
    
    	"example.com/hello"
    )
    
    func main() {
    	fmt.Println(hello.Hello)
    }

From Emacs, the `example.com/hello` is not added.

- M-: (getenv "GOPATH")
    
    "/home/enzoc/App/go_path"

- M-: (buffer-file-name)

    "/home/enzoc/App/go_path/src/github.com/enzochiau/go16vendor/main.go"

**Comment by kostya-sh** [comment]
I have tested this just now with the latest version of goimports and it works ("example.com/hello" is inserted on save). Possibly has been fixed by https://github.com/golang/tools/commit/c86fe5956d4575f29850535871a97abbd403a145 

To install the latest version of goimports run

    go get -u golang.org/x/tools/cmd/goimports

**Comment by psanford** [comment]
I'm going to close due to lack of activity. I'm comfortable saying a properly configured emacs+goimports works with vendor directories.
