### ISSUE TITLE
symbolic links in path names

### ISSUE THREAD

**Issue by cpaulbond** [dominikh/go-mode.el#138]
Because of the way we have our go projects configured we symlinks to directory outside the normal go path which contain code.  I have found that when I jump to a definition and it's the first time visit to the file will be opened with the name outside the path.  I have traced the problem back to using file-truename over expand-file-name.  You can see an example of this problem in godef--call.  When called with a buffer with a file name in the go path (but containing a symlink in the path) the resulting file name will be outside the path and chaos results.

Since file-truename calls expand-file-name to do almost all the work would it be possible to switch to using expand-file-name?  I have patched my personal copy, and I not had any issues, but I am sure there are lots of things in go-mode that I have not tried yet.

**Comment by dominikh** [comment]
There are setups where we need to follow symlinks. These setups usually involve symlinks from outside a GOPATH to inside a GOPATH, in particular when the value of GOPATH itself is a symlink. We're not actually calling file-truename for the effects that expand-file-name has, but explicitly for the symlink following.

The go tool itself has a history of not fully supporting symlinks (for example `go list ...` will not work properly), so I am inclined to not make any changes in go-mode and to suggest that you maintain your own version. It should also be noted that other Emacs packages for Go, such as the integration with Guru, use the same logic as go-mode.

**Comment by cpaulbond** [comment]
Thanks for the feedback.  I wondered if there where problems with symlinks
and now I know there is a deeper problem and will follow your suggestion.
In the end it looks like we need to rethink how we are using symlinks so we
can avoid the problem.

On Fri, May 20, 2016 at 2:53 AM, Dominik Honnef <notifications@github.com>
wrote:

> There are setups where we need to follow symlinks. These setups usually
> involve symlinks from outside a GOPATH to inside a GOPATH, in particular
> when the value of GOPATH itself is a symlink. We're not actually calling
> file-truename for the effects that expand-file-name has, but explicitly for
> the symlink following.
>
> The go tool itself has a history of not fully supporting symlinks (for
> example go list ... will not work properly), so I am inclined to not make
> any changes in go-mode and to suggest that you maintain your own version.
> It should also be noted that other Emacs packages for Go, such as the
> integration with Guru, use the same logic as go-mode.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dominikh/go-mode.el/issues/138#issuecomment-220531137>
>



-- 
C. Paul Bond, cpaulbond@gmail.com
