### ISSUE TITLE
Renaming of variable identifiers

### ISSUE THREAD

**Issue by ksrb** [dominikh/go-mode.el#141]
Anything on the road map for a function to find and replace variable identifiers across a package?

Similar to something that [vim-go](https://github.com/fatih/vim-go#features) has 😄 .

**Comment by dominikh** [comment]
The functionality exists in external tools and scripts. Install gorename and load `./refactor/rename/go-rename.el` from the /x/tools repository.

**Comment by ksrb** [comment]
@dominikh thanks, this works.

For use-package users:
```elisp
(use-package go-rename)
```
