### ISSUE TITLE
Godef not working for code in path

### ISSUE THREAD

**Issue by ksrb** [dominikh/go-mode.el#142]
It works on the std lib code (fmt.Errorf) but not my own code, I suspect it's a result of various environment variables not being found.

**System**
OS X El Captain

**Emacs**
```elisp
(go-root-and-paths)
;; ("/usr/local/Cellar/go/1.6/libexec" "")

(getenv "GOROOT")
;; nil
```

**Bash**
```bash
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ksuen/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"

echo 'package foo; import "fmt"; func fn() { fmt.Println() }' | godef -i -o 45
/usr/local/Cellar/go/1.6/libexec/src/fmt/print.go:263:6
```

Related issue https://github.com/dominikh/go-mode.el/issues/134

**Comment by dominikh** [comment]
Your Emacs isn't inheriting GOPATH. If you only set the environment variable in your bashrc, but start Emacs via the OS X GUI, these two will work with different sets of environment variables.

**Comment by ksrb** [comment]
@dominikh thanks for the quick debug, helped me to narrow my googling.

A solution is given in this blog post: 
http://tleyden.github.io/blog/2014/05/22/configure-emacs-as-a-go-editor-from-scratch/

For the use-package users:
```elisp
(use-package go-mode
  :init
  (setenv "GOPATH" "[absolute path to GOPATH]")
```
