### ISSUE TITLE
GOPATH could be set for local buffer

### ISSUE THREAD

**Issue by vincentbernat** [dominikh/go-mode.el#145]
Hey!

It's possible to set an environment variable affecting only a buffer:

```lisp
(make-local-variable 'process-environment)
(setq process-environment (cons (format "GOPATH=%s" gopath) process-environment))
```

It should help setting up an appropriate GOPATH since this can be done when loading the major mode for the buffer. I am doing this:

```lisp
(defun vbe:go-mode-setup-gopath ()
  "Setup GOPATH from guessed possibilities."
  (let ((gopath (or (go-guess-gopath (current-buffer))
                    (go-original-gopath))))
    (make-local-variable 'process-environment)
    (setq process-environment (cons (format "GOPATH=%s" gopath) process-environment))))

(add-hook 'go-mode-hook 'vbe:go-mode-setup-gopath)
```

**Comment by dominikh** [comment]
Setting environment variables local to a buffer doesn't work very well. A lot of things in Emacs operate in different buffers. Compilation, godef and so on all create their own buffers, and buffers do not inherit local variables. Setting GOPATH locally would thus result in a lot of inconsistent state, where a lot of code will be using the global value instead.

**Comment by vincentbernat** [comment]
OK, good to know. It worked for checkers, I assumed it would work for other things as well.
