### ISSUE TITLE
goimports can't tell the complete filename when used with go-mode.el

### ISSUE THREAD

**Issue by bradfitz** [dominikh/go-mode.el#146]
Most editors run goimports on the file directly.

go-mode.el's gofmt function on the other hand writes the buffer to a tempfile and then runs goimports on the temp filename. This is problematic because goimports needs to look around the user's $GOPATH and figure out which things can be used and not used (for "internal" and "vendor" directories). This is what motivated the addition of the `-srcdir` flag to goimports.

Unfortunately, `-srcdir` isn't enough. I also need to know the filename for some in-development feature additions to goimports. (see https://golang.org/cl/23444 from @briantkennedy)

I don't want to add new flags to goimprots.

I propose to change goimports to let `-srcdir` mean either a complete filename, or a directory. goimports can detect what it is.

Then the change I propose to go-mode.el is:

```patch
diff --git a/go-mode.el b/go-mode.el
index 8acc0e1..9705e76 100644
--- a/go-mode.el
+++ b/go-mode.el
@@ -1152,7 +1152,7 @@ with goflymake \(see URL `https://github.com/dougm/goflymake'), gocode
           (when (and (gofmt--is-goimports-p) buffer-file-name)
             (setq our-gofmt-args
                   (append our-gofmt-args
-                          (list "-srcdir" (file-name-directory (file-truename buffer-file-name))))))
+                          (list "-srcdir" (file-truename buffer-file-name))))) ; see https://github.com/dominikh/go-mode.el/issues/146
           (setq our-gofmt-args (append our-gofmt-args
                                        gofmt-args
                                        (list "-w" tmpfile)))
```

/cc @adonovan

**Comment by dominikh** [comment]
Awful name for the flag then, but I'm fine with making that change in go-mode.

**Comment by bradfitz** [comment]
It's a terrible name for the flag. I agree.

Fortunately it's only used by editors, and basically only used by go-mode.el.

A bad name is better than the pain caused by alternative fixes.

**Comment by dominikh** [comment]
> Fortunately it's only used by editors, and basically only used by go-mode.el.

For what it's worth, vim-go also uses the flag. As for some historical context on why we use temporary files instead of operating on the file directly, there are two reasons.

1. We can format buffers that aren't attached to real files
2. Emacs before version 25 would lose the entire undo history if you reloaded a file, and the cursor position might be affected in weird ways. We process the diff output which maintains a history and the cursor.

**Comment by bradfitz** [comment]
@adonovan speculated exactly both of those two reasons. :-)

**Comment by bradfitz** [comment]
> For what it's worth, vim-go also uses the flag. 

That's good to hear. I'll file a bug there.

**Comment by dominikh** [comment]
@bradfitz I've lost track of this issue. What's left for you to do, and are there still changes to go-mode required?

**Comment by bradfitz** [comment]
Did you do make a change already for it? I believe my patch in the top comment is still the best plan.

**Comment by dominikh** [comment]
Now I have, thanks.
