### ISSUE TITLE
Indentation in raw string literals

### ISSUE THREAD

**Issue by dolzenko** [dominikh/go-mode.el#147]
Hi @dominikh, big thank you for your work! Not sure if this is OK to ask questions here, but I didn't find anything about that in README. My question is if indentation of the raw string literal in snippets like this

```
func f() {
  s := `my
    long
    string
`
}
```

can be controlled? The problem is that currently its using spaces which is somewhat inconsistent with the rest of the tab based indents in the Go source.

**Comment by dominikh** [comment]
go-mode isn't doing any kind of indentation in raw strings. Indentation in raw strings is significant as it becomes part of the actual value, and whether tabs, spaces or neither should be used depends on what you actually need in the string. go-mode will not touch the indentation in raw strings at all, and new lines will start in the first column.

**Comment by dolzenko** [comment]
Reasonable, thanks!
