### ISSUE TITLE
`go-mode` tabifies incorrectly

### ISSUE THREAD

**Issue by Gnouc** [dominikh/go-mode.el#153]
With simple file like:
```go
package t

var _ = `
    x
`
```

---

```sh
% cat -et t.go
package t$
$
var _ = `
     x$
`$
```

Save it in emacs with `go-mode` enabled produce:
```sh
% cat -et t.go
package t$
$
var _ = `
^Ix
`$
```

Note 4 spaces, which is my `tab-width` are expanded to one tab.

`go-mode` seems to set `indent-tabs-mode` to true.

**Comment by dominikh** [comment]
I cannot reproduce the issue. Saving that file, neither with nor without the gofmt hook enabled, will convert spaces to tabs. indent-tabs-mode alone is not responsible for this. Are you running some other hook, such as tabify, on save? Or are you using smart tabs?

**Comment by Gnouc** [comment]
@dominikh No, here's my emacs config https://github.com/Gnouc/emacs.d

If I remove the line in `go-mode.el`, it works as expected.

**Comment by dominikh** [comment]
Are you able to reproduce the issue in an `emacs -Q` session, with just go-mode.el loaded?

**Comment by Gnouc** [comment]
@dominikh I'm away from my laptop, will try it tonight.

**Comment by Gnouc** [comment]
@dominikh I can not reproduce with `emacs -Q` with only `go-mode.el` loaded.

I found the culprit, it's `ws-butler`, which auto replace spaces by tabs if `ident-tabs-mode` is true, and vice versa.

Sorry for this annoying.
