### ISSUE TITLE
go-rename seems broken these last several days

### ISSUE THREAD

**Issue by xoba** [dominikh/go-mode.el#155]
i filed golang/go#17468 about it, not sure if folks here would like to have a look as well.

basically i've been a happy user of go-rename for a while now, also of go-mode generally, but recently go-rename has stopped working and produces errors like `Symbol's function definition is void: list*`.

thanks!

**Comment by dominikh** [comment]
I've mailed https://go-review.googlesource.com/#/c/31471/ – going to close this issue here because go-rename is, at the moment, still part of x/tools, not go-mode.

**Comment by xoba** [comment]
thanks, i've really gotta learn me some emacs-lisp :+1:
