### ISSUE TITLE
go-mode-hook isn't called？

### ISSUE THREAD

**Issue by hgl** [dominikh/go-mode.el#160]
I'm pretty new to elisp, hope I didn't do anything wrong.

I added this to my `init.el`
```
(add-hook 'go-mode-hook (lambda ()
  (local-set-key (kbd "s-O") #'go-goto-imports)))
```

After reopening emacs, the binding didn't kick in when I switched to a go buffer (I have desktop save mode enabled, and I'm pretty sure the go major mode was on for that buffer).

I checked the `go-mode.el` source code and it seems the mode hook was never called? Or I should use another method to define mode specific bindings?

**Comment by dominikh** [comment]
The hook is called automatically by emacs, based on the major mode that go-mode defines; we don't need to call it manually. And in fact, the hook is working here.

I'm afraid that "pretty sure the go major mode was on for that buffer" won't cut it. Can you confirm that it was indeed turned on?

**Comment by hgl** [comment]
Thanks for the quick reply.

`C-h v major-mode` in that buffer gave `Its value is ‘go-mode’`.

Not sure if it's related, but I have this previously defined:

```
(global-set-key (kbd "s-O") #'find-file-at-point)
```

I suppose local bindings should shadow global bindings?

**Comment by hgl** [comment]
In the go buffer, `s-O` ran `find-file-at-point` but not `go-goto-imports` (can confirm that by executing `C-h k s-O`, and it gave `find-file-at-point`).

I tried manually evaluating `(local-set-key (kbd "s-O") #'go-goto-imports)` in that buffer, and it worked (`C-h k s-O` gave `go-goto-imports`).

**Comment by hgl** [comment]
Seems to have something to do with broken desktop save file.

It's working now.
