### ISSUE TITLE
Visualized escape analysis

### ISSUE THREAD

**Issue by JAremko** [dominikh/go-mode.el#162]
I think it would be great to have similar feature to the coverage statistic(display code coverage with an indirect buffer) but for escape analysis:
Example [(source)](http://blog.rocana.com/golang-escape-analysis):

``` go
package main

type S struct {}

func main() {
  var x S
  y := &x
  _ = *identity(y)
}

func identity(z *S) *S {
  return z
}
```

>  we can run the compiler with -gcflags '-m', which will print verbose escape analysis information:   

```
./escape.go:11: leaking param: z to result ~r1
./escape.go:7: main &x does not escape
```

Can we use this data to visual differentiate escaped/non-escaped/moved_to_heap variables?

**Comment by dominikh** [comment]
Sure, that sounds like a cool idea. Unfortunately I probably won't have time to work on this in 2016, but if anyone would like to submit a patch, that'd be great.

**Comment by dominikh** [comment]
gopls supports this in the form of code lenses. As reliance on LSP is only increasing, there's not much reason for us to implement this in go-mode.
