### ISSUE TITLE
How to disable annoying *Gofmt Errors* buffer?

### ISSUE THREAD

**Issue by dineshbhosale** [dominikh/go-mode.el#163]
After executing `gofmt-before-save` command, it opens a new window displaying various errors message, how can I disable this window from opening ?

**Comment by dineshbhosale** [comment]
Adding this line to my config solved my problem , I recommend to add this to README file so others can use it, feel free to close this issue.

```lisp
(setq gofmt-show-errors nil)
```

**Comment by dominikh** [comment]
The option is documented in Emacs's customization system (`M-x customize-group RET go RET`). The README does not contain a copy of all of the mode's documentation, just an introduction to the project.

I'm glad you were able to fix your problem.
