### ISSUE TITLE
Feature request: GoAddTags

### ISSUE THREAD

**Issue by pengux** [dominikh/go-mode.el#164]
Similar to [vim-go's GoAddTags function](https://github.com/fatih/vim-go/blob/master/CHANGELOG.md#18-july-31-2016) which add field tags for the fields of a struct automatically based on the field names.

**Comment by syohex** [comment]
[NOTE] I implement go-add-tags https://github.com/syohex/emacs-go-add-tags

**Comment by dominikh** [comment]
We won't implement this in go-mode. We may depend on syohex's package in an upcoming go-ide package, though.
