### ISSUE TITLE
command to comment out / uncomment a block of code

### ISSUE THREAD

**Issue by helinwang** [dominikh/go-mode.el#171]
Are there command to comment out/ uncomment a block of code?
I just begin to learn emacs, from googling, c-c c-c seems to be the hotkey for cc-mode. But seems it does not work for go-mode.

**Comment by dominikh** [comment]
You want `comment-dwim`, or the more manual `comment-region` and `uncomment-region`. `comment-dwim` is bound to `M-;` by default.

**Comment by helinwang** [comment]
Thanks! That's what I wanted.
