### ISSUE TITLE
wrapping long lines.

### ISSUE THREAD

**Issue by amosbird** [dominikh/go-mode.el#172]
Since `go fmt` won't break long lines, I wonder if we could have this feature in `go-mode`.

**Comment by dominikh** [comment]
I don't think that this is worth the effort. Go code doesn't stick to a strict "lines must not be longer than [arbitrary number of characters]" rule. Instead, lines should be wrapped in a way that is the most readable, and we cannot really programmatically determine what the most readable form is.

**Comment by amosbird** [comment]
hmm, that's pretty vague. Are there any existing code style rules that determine this?

**Comment by dominikh** [comment]
It is vague because it's based on the idea of "use your best judgement". The official, written-down version of that can be found at https://github.com/golang/go/wiki/CodeReviewComments#line-length

**Comment by amosbird** [comment]
Ok, I see.
