### ISSUE TITLE
reuse a single *godoc* buffer for godoc-at-point

### ISSUE THREAD

**Issue by petergardfjall** [dominikh/go-mode.el#180]
Currently, `godoc-at-point` opens a separate buffer for each call. Such a buffer is named something similar to `*godoc /path/to/ Type*`. I always seem to forget to close these buffers, so they quickly pile up. 

I would much prefer having all these `godoc-at-point` calls displaying in a single buffer, say `*godoc*`, whose contents would be replaced for every call. If the old behavior is preferred (one separate buffer per call), I would love to see an option. For example

    ;; reuse a single *godoc* buffer to display godoc-at-point calls
    (setq go-godoc-reuse-buffer t)  

Would this make sense?

As a side-note, these buffers seem to also cause problems for me with the neotree project explorer open. Successive calls to `godoc-at-point` opens/splits buffers in a somewhat irrational way (the `*godoc*` buffers, which I am used to seeing at the bottom of the screen, wander around and all of a sudden `*scratch*` and `*Messages*` appear). I suspect that this is due to some weirdness in neotree, but it works fine for me, for example, in `python-mode` and I suspect that it would work better in `go-mode` if only a single `*godoc*` buffer was being reused.

**Comment by paralin** [comment]
The way Godoc works right now really sucks. It seems to just pick a random window, then replace whatever buffer is there with a *brand new* Godoc buffer every time. I'm used to pressing K in vim to see the documentation at the point, but I've found myself wasting a lot of time hitting the key, realizing one of my windows I was using was just clobbered, deleting the Godoc buffer, opening up the buffer I had before.....

It's cumbersome. Use a temporary buffer like Flycheck.

**Comment by oleorhagen** [comment]
Well, if godoc uses display-buffer, it's not that hard to modify

**Comment by lawrsp** [comment]
@petergardfjall 
by the way,
when I use godoc-at-point with neotree project explorer opened, the result shows in a pop up window.
wired..

**Comment by petergardfjall** [comment]
@lawrsp I'm seeing the same behavior (the result being opened in a different window, or "frame" in emacs terminology). Very irritating behavior IMHO. It seems this behavior is fixed by #168. I would really like to see that pull request merged..

**Comment by psanford** [comment]
Lets keep this issue focused on the original issue of reusing a single buffer instead of creating new buffers per unique godoc invocation.

There seems to be some inconsistency between what other things in emacs do. For example `(man)` creates a new buffer per unique invocation. However `(describe-function)` and friends reuse a single buffer named `*Help*`. 

I'd be open to making this customizable if someone wants to send a pr.

**Comment by petergardfjall** [comment]
I've opened a PR. https://github.com/dominikh/go-mode.el/pull/295

**Comment by petergardfjall** [comment]
Ping @psanford. I created a PR that solves this issue. Please take a look when time permits!

**Comment by psanford** [comment]
Thanks for the pr!
