### ISSUE TITLE
Support Go templating syntax

### ISSUE THREAD

**Issue by bassu** [dominikh/go-mode.el#184]
It would be great to have `go-mode` support syntax highlighting for `.tmpl` files (without code completion), kinda like `vim-go`.
 
I guess code completion for objects under `{{.}}` cursor would be difficult without knowing the objects passed to Execute beforehand!

**Comment by dominikh** [comment]
I'd accept patches for this, but it's not a high priority. At least one 3rd party mode, web-mode, supports Go templates.

**Comment by bassu** [comment]
Thanks! I didn't know that. The `web-mode` seems to be working.
So far, so good. 
Closing 🍺
