### ISSUE TITLE
customize GOOS/GOARCH/etc

### ISSUE THREAD

**Issue by mdempsky** [dominikh/go-mode.el#187]
It would be nice to be override GOOS/GOARCH/etc variables when trying to understand non-portable code. Unfortunately, this can't be done via go-guru-command, because it gets shell quoted into a single argument.

I was able to get the effect I needed by changing `(list go-guru-command ...)` in go-guru-command to `(list "env" "GOOS=openbsd" go-guru-command ...)`.

My immediate use is for guru, but it's potentially useful for almost any Go tool that uses go/build.

**Comment by dominikh** [comment]
You can simply set the environment variables via `M-x setenv` and it'll work for all tools (gocode, godef, guru, ...)

**Comment by mdempsky** [comment]
Interesting, that seems like it should work. I'll reopen if not. Thanks!
