### ISSUE TITLE
go-remove-unused-imports doesn't remove any imports

### ISSUE THREAD

**Issue by markcol** [dominikh/go-mode.el#19]
If I edit an existing Go file, and add package to the import list that isn't referenced anywhere, then invoke go-remove-unused-imports, no imports are removed, even though the compiling the file results in an unused import error.

Using the code with go-flymake, gocode, and auto-complete enabled. I haven't tried turning them off yet.

**Comment by Gnouc** [comment]
I face the same issue with `go-mode-20150817.2318`. With these code:
```
// Author: CuongLM
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Hello world!")
}
```

Then running `go-remove-unused-imports` return `Removed 0 imports`. Also eval `(go-unused-imports-lines)` return `nil`.

**Comment by dominikh** [comment]
Please run "go build -o /dev/null path/to/file.go" in a terminal (making sure GOROOT and GOPATH are identical to what Emacs sees) and paste the output here.

**Comment by Gnouc** [comment]
@dominikh: Here is it
```
$ go build -o /dev/null test.go 
# command-line-arguments
./test.go:6: imported and not used: "os"
```
`GOROOT` and `GOPATH` are identical to emacs because I used `exec-path-from-shell`, and other features of `go-mode` worked well.

**Comment by dominikh** [comment]
1) What is the result of evaling `buffer-file-truename`
2) Does go-remove-unused-imports work when you name the file `foobar.go`?

**Comment by Gnouc** [comment]
@dominikh 
1) `(print buffer-file-truename)` return `~/bin/test.go`.
2) Running `cp test.go foobar.go`, open `foobar.go` and running `go-remove-unused-imports`, still return `Removed 0 imports`.

**Comment by dominikh** [comment]
Please eval this code:

```
(split-string (shell-command-to-string
               (concat go-command
                       (if (string-match "_test\.go$" buffer-file-truename)
                           " test -c"
                         " build -o /dev/null"))) "\n")
```

**Comment by Gnouc** [comment]
@dominikh It returned
```
("cant't load package: package .: C source file not allowed when not using cgo or SWIG: shell.c test.c" "")
```

where `shell.c` and `test.c` are regular files in the same directory with `test.go`.

**Comment by Gnouc** [comment]
I confirmed that!

Copied `test.go` to `/tmp/test/test.go`, go to `/tmp/test`, open `test.go` and `go-remove-unused-imports` worked as expected.

The error above is exactly I got when running `go build -o /dev/null` from my shell in `~/bin/` .

Should I go with a pull request?

**Comment by dominikh** [comment]
I'm working on a fix.

**Comment by Gnouc** [comment]
@dominikh Thanks for quick response! :+1:

**Comment by dominikh** [comment]
@Gnouc I've pushed a (hopefully) fixed version to master. Please confirm that it works as expected.

**Comment by Gnouc** [comment]
@dominikh Work perfect now!
