### ISSUE TITLE
Add `use-local-map` in mode declaration

### ISSUE THREAD

**Issue by Ambrevar** [dominikh/go-mode.el#191]
Calling `(local-set-key ...)` will only take effect on the current Go buffer.
From the function documentation:

> The binding goes in the current buffer’s local map, which in most
> cases is shared with all other buffers in the same major mode.

"in most cases" refers to modes that set a major mode map. See `cc-mode.el`:

```
(define-derived-mode c-mode prog-mode "C"
  "Major mode for editing C code.

[...]"
  (c-initialize-cc-mode t)
  (set-syntax-table c-mode-syntax-table)
  (setq local-abbrev-table c-mode-abbrev-table
	abbrev-mode t)
  (use-local-map c-mode-map)
	[...]
```

Currently `go-mode-map` is a buffer local map (if I understood correctly).

Is there any reason for go-mode not to use a major mode map?

**Comment by dominikh** [comment]
We define go-mode-map, which is picked up by define-derived-mode, which itself calls use-local-map with that map; the name is being inferred by the mode's name. More specifically, define-derived-mode is a large macro that generates code for setting syntax tables, keymaps, and so on.

I'm not sure why cc-mode is calling use-local-map itself, but in our case, it is being done implicitly.

I'm not quite sure why you mention local-set-key. I'm also not sure what the actual problem you're experiencing is; you have proposed a solution without a problem.

**Comment by Ambrevar** [comment]
I understand there are some underlying macros and I don't claim to be Emacs API expert, but I don't think `use-local-map` is called for Go. I could be wrong.

The problem is as mentioned in the quote of `local-set-key`'s doc, that the current local map (which is retrieved by `(current-local-map)` and is different from `go-mode-map`) is not shared across Go buffers.

Let me detail the problem:

`local-set-key` comes in handy to set mode-specific bindings (and not just buffer-local).
I want to set some Go bindings from my config file `mode-go.el` that I `require`:

	(add-hook 'go-mode-hook (lambda () (require 'mode-go)))

In `mode-go.el`, I set among others:

	 (local-set-key (kbd "M-.") #'godef-jump)

That binding will be seen in the first buffer only, while any subsequent Go buffer will be oblivious to it.

Simple steps to reproduce:

- Open a Go buffer.
- Call `(local-set-key (kbd "M-.") #'godef-jump)` (or any other binding that you haven't already defined.
- Switch to another Go buffer: the binding is _not_ set.

**Comment by dominikh** [comment]
Your go-mode-hook will run every time go-mode is activated, so at least once per buffer. Even if the keymap moodification is local to a single buffer, the same modification will be applied to all Go buffers, as each activates go-mode.

As for us calling use-local-map, you can use macroexpand on our define-derived-mode macro to see that it does, unconditionally, call use-local-map.

As for why the local map is unique per Go buffer, I couldn't tell you.

**Comment by Ambrevar** [comment]
My Go hook only calls the `require` function, which runs only once, and thus the bindings are set only once.

It's good practice to not clutter the hooks when there is no need, so I only set buffer local variables in my hooks. Key bindings are supposed to be part of the mode configuration, not the buffer.

**Comment by dominikh** [comment]
You could always add the keybinding to go-mode-map directly. Alternatively, if you can figure out why we're not sharing the map across buffers, I'd be happy to fix that.

**Comment by Ambrevar** [comment]
I find it simpler to just add this to my config file for now:

	(use-local-map go-mode-map)

I don't think there is anything to fix beside that.
It matches the documentation and Emacs' standard major modes implementation.

True so, I am not quite sure I understand what happens under the hood: it seems that Emacs major-mode init macros create a buffer-local copy of `go-mode-map` and set it to be the buffer local map.

The `describe-key` command does not return any associated keymap to the bindings defined for those buffer local keymaps.

**Comment by Ambrevar** [comment]
You were right: it seems that many modes do not invoke `use-local-map` while it still behaves as expected (e.g. python-mode, nroff-mode).

Something is wrong in go-mode.

**Comment by psanford** [comment]
I'm going to close this due to lack of activity. Feel free to reopen if you can identify something concrete that is wrong in go-mode.
