### ISSUE TITLE
How to use go-guru with go-mode

### ISSUE THREAD

**Issue by helinwang** [dominikh/go-mode.el#192]
Hi, I have installed go-mode using `use-package`, but I can not find any `go-guru*` command using `M-x`.
I saw `go-guru.el` in the repo, so I thought go-guru is installed with go-mode? Should I do any special step to install go-guru?

**Comment by LMMilewski** [comment]
This should work:

```
(use-package go-guru
  :demand t)
```

**Comment by dgellow** [comment]
@LMMilewski Doesn't work for me.

**Comment by LMMilewski** [comment]
Follow the steps below and tell me whether that worked:

1. Pull latest versions of go-mode and use-package
```
$ mkdir /tmp/elisp
$ cd /tmp/elisp
$ git clone git@github.com:dominikh/go-mode.el.git go-mode
$ git clone git@github.com:jwiegley/use-package.git
```

2. Start emacs without your configs:
```
$ emacs -Q
```

3. Evaluate the following in the scratch buffer:

```
(add-to-list 'load-path "/tmp/elisp/use-package")
(require 'use-package)

(use-package go-mode
  :load-path "/tmp/elisp/go-mode")

(use-package go-guru)
```

4. Check that go-guru- commands are available after M-x

**Comment by dgellow** [comment]
@LMMilewski Your instructions seem to work, thank you 👍 Now I will try to figure out why it doesn't work with my config  ¯\_(ツ)_/¯

**Comment by dgellow** [comment]
Oh, I know why it doesn't work! I just realised now by checking the [file on MELPA](https://melpa.org/#/go-mode) that [go-guru is a different package](https://melpa.org/#/go-guru). By installing it explicitly from `package.el` everything seems to work fine.

Thank you for your time 🙇🏻
