### ISSUE TITLE
How to change tag width?

### ISSUE THREAD

**Issue by cg31** [dominikh/go-mode.el#193]
After installing go-model, the tab width is 8 by default. How can I change it to 4?

I skimmed the code but didn't find any clue.

**Comment by dominikh** [comment]
Not specific to go-mode; set the tab-width variable. See `C-h v RET` for more information.

**Comment by cg31** [comment]
I got it...

(add-hook 'go-mode-hook
    (lambda ()
        (setq tab-width 4)))
