### ISSUE TITLE
Integrate go-present-mode.el with go-mode.el

### ISSUE THREAD

**Issue by LMMilewski** [dominikh/go-mode.el#197]
Hi, I wrote a major mode for editing Go present slides. I want to open-source it and I'm considering two options:
 1. make it a part of go-mode
 2. make it a standalone mode

I'm leaning towards 1. What do you think? Would you be open to reviewing a PR?

**Comment by dominikh** [comment]
Hi,

I'll be out of order till some time next week. But then I'll be happy to look at your code and see what makes the most sense.

**Comment by LMMilewski** [comment]
I created a PR at https://github.com/dominikh/go-mode.el/pull/199

**Comment by LMMilewski** [comment]
@dominikh Do you think that you'll have a chance to take a look at the PR in the near future? I think that the key questions is whether go-present-mode is a good fit for go-mode or not. As to actual code reviews, we could do them in parts over a longer period of time if that works for you better.

**Comment by dominikh** [comment]
@LMMilewski If it's well implemented it's a good fit for go-mode. I'll try and look at the implementation on Friday.
