### ISSUE TITLE
can not use ctrl+v to paste when go mode is active.

### ISSUE THREAD

**Issue by helinwang** [dominikh/go-mode.el#198]
It's very strange, when go mode is active, I can not use ctrl + v to paste. And can hear error sound "dong", "dong". The status bar shows "No more Flycheck errors", or sometimes shows "Moved back before first error".
Sometime paste works, but if the content in my clipboard is `foo`, `201~200~foo` got pasted.

When I turn off go mode, everything works fine.

I found out if I turn off:
```lisp
(local-set-key (kbd "M-]") 'next-error)         ; Go to next error (or msg)                                                                                                          
(local-set-key (kbd "M-[") 'previous-error)     ; Go to previous error or msg   
```
everything turns fine. Any solution to fix this?

**Comment by dominikh** [comment]
This sounds like a flycheck issue, not a go-mode issue? Can you reproduce this in a vanilla Emacs (emacs -Q) that has loaded nothing besides go-mode.el?

**Comment by psanford** [comment]
I'm going to close this due to lack of activity. Feel free to reopen if you are still having the issue and can reproduce in a clean emacs environment.
