### ISSUE TITLE
Doesnt work on osx at all.

### ISSUE THREAD

**Issue by NikosEfthias** [dominikh/go-mode.el#202]
Go works perfectly from command line gofmt and goimports are installed and working, but when i try gofmt in go-mode i get the error message telling gofmt command couldnt be found

**Comment by dominikh** [comment]
See https://www.emacswiki.org/emacs/ExecPath and https://emacs.stackexchange.com/questions/10722/emacs-and-command-line-path-disagreements-on-osx

**Comment by NikosEfthias** [comment]
Thanks. Now everything works properly. Is there a way to use goimports rather than gofmt ?

**Comment by dominikh** [comment]
Customize the `gofmt-command` variable.

**Comment by NikosEfthias** [comment]
I am super new to emacs thank you for your help 👍
