### ISSUE TITLE
godef-jump "escapes" indirect buffer

### ISSUE THREAD

**Issue by imsodin** [dominikh/go-mode.el#206]
When I use godef-jump within an indirect buffer ("main.go<2>") I always end up in the "root" buffer ("main.go") which interrupts my workflow. I would expect to end up in the same (indirect) buffer when the definition is within the same buffer.

**Comment by dominikh** [comment]
Can you further explain your workflow, how and why you create these indirect buffers?

**Comment by imsodin** [comment]
I usually edit a section and come unto something that also needs editing too or just investigation, so I open an indirect buffer in a new window, giving access and easy switching between both buffers. As to why I use an indirect buffer instead of just another window with the same buffer: I don't remember the exact issue I had, but something with navigation, and indirect buffers was the solution.

**Comment by dominikh** [comment]
I see. I will look into that and if godef-jump can be tuned.

Heck, I may even adopt the workflow, as it solves two problems: 

1. ido-switch-buffer sorts visible buffers to the end of the list, which makes it annoying to switch between two buffers if one of them is also visible in another window.
2. The position of point, as is restored when switching between buffers, is only stored once per buffer, which can make it really difficult to work with the same buffer in multiple windows.

**Comment by imsodin** [comment]
Nice :)  
Another thing I noticed in the meantime: go-rename also only works in the "main" buffer, not in indirect ones. Maybe it's the same underlying mechanism.

**Comment by dominikh** [comment]
godef and gorename have largely been replaced by LSP.
