### ISSUE TITLE
godef-jump doesn't work if using on function declared in the same file

### ISSUE THREAD

**Issue by robert-zaremba** [dominikh/go-mode.el#209]
How to reproduce:

1. copy this file: https://play.golang.org/p/h6o-C13nSf
2. move your cursor to line 6 - on the `myfunction` call
3. call emacs' `godef-jump`

Emacs will create a new buffer called `9:6` instead of jumping to the line 9 in current file.

Environment:
Emacs 25.2
go-mode 20170726.555

**Comment by dominikh** [comment]
Cannot reproduce. And I'd have been surprised if I could, it's a feature that hundreds of people use daily.

You'll have to provide more information. Operating system? Actual, full name of the file?

**Comment by dominikh** [comment]
Timed out.

**Comment by pashh** [comment]
I met the same issue and not understand what is going on.

**Comment by muirdm** [comment]
@pashh can you create a new issue with a full description and steps to reproduce?

**Comment by pashh** [comment]
I found the how to fix it.
I'm not quite familiar how the godef-jump working, but in my case
M-x go-set-project made it work again.
If you have a clue about it, please let me know

**Comment by muirdm** [comment]
It sounds like your environment (e.g. GOPATH) isn't set in Emacs. You can try starting Emacs from the terminal or using [this](https://github.com/purcell/exec-path-from-shell) package.
