### ISSUE TITLE
go-guru doesn't work on Windows

### ISSUE THREAD

**Issue by seagle0128** [dominikh/go-mode.el#218]
Windows 10, GNU Emacs 25.3, Go 1.9.1

`go-guru` returns the error below, but `godef` works well.

```elisp
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  go-guru--goto-byte-column(256)
  go-guru--goto-pos("C:\\Go\\src\\fmt\\print.go:256:6" nil)
  go-guru-definition()
  funcall-interactively(go-guru-definition)
  call-interactively(go-guru-definition nil nil)
  command-execute(go-guru-definition)
```

**Comment by seagle0128** [comment]
Seems `go-guru--goto-pos` doesn't handle the file path like "C:\\Go\\src\\fmt\\print.go:256:6". After splitting, the file path is "C"! And the line position is incorrect as well.

**Comment by g2flyer** [comment]
Following patch would make go-guru.el work on windows ...
$ diff -u go-guru.el.*
--- go-guru.el.orig     2018-01-22 12:24:52.225719700 -0800
+++ go-guru.el.patched  2018-01-22 12:25:36.845977500 -0800
@@ -324,6 +324,11 @@
   "Find the file containing the position POSN (of the form `file:line:col')
 set the point to it, switching the current buffer."
   (let ((file-line-pos (split-string posn ":")))
+    (if (eq system-type 'windows-nt)
+       (let ((first-file-line-pos (car file-line-pos)))
+         (if (string-match-p "^[a-z]$" first-file-line-pos);; looks like a drive name ...
+             (setq file-line-pos (cdr file-line-pos));; .. so remove it
+           )))
     (funcall (if other-window #'find-file-other-window #'find-file) (car file-line-pos))
     (goto-char (point-min))
     (forward-line (1- (string-to-number (cadr file-line-pos))))

**Comment by seagle0128** [comment]
@g2flyer It looks good. Would you please submit a PR?

**Comment by g2flyer** [comment]
@seagle0128 i just created a pull request (hope it's ok, i have to admit it's my first github pull request :-)

**Comment by dominikh** [comment]
guru is deprecated.
