### ISSUE TITLE
Go guru Symbol's value as variable is void on emacs

### ISSUE THREAD

**Issue by yltozh** [dominikh/go-mode.el#220]
``(require` 'go-guru)``
``(add-hook 'go-mode-hook #'go-guru-hl-identifier-mode)``

> Symbol's value as variable is void: <!DOCTYPE                                                                                                     
> To ensure normal operation, you should investigate and remove the           
> cause of the error in your initialization file.  Start Emacs with           
> the ‘--debug-init’ option to view a complete error backtrace

Go guru doesnt work. What's wrong?

**Comment by dominikh** [comment]
Download the elisp file, not an HTML file displaying the source code.
