### ISSUE TITLE
Update README now that go-mode-autoloads.el is gone

### ISSUE THREAD

**Issue by pmatos** [dominikh/go-mode.el#222]
When installing through melpa, I have:

```
...
(package-initialize)

...
(require 'go-mode-autoloads)
```

and get `Required feature 'go-mode-autoloads' was not provided`.
I can see the file `go-mode-autoloads.el` installed. I specifically do not have any add-to-path since with melpa, you shouldn't. `package-initialize` should sort that out and yet, it seems that something went wrong becase it's not working. Couldn't this be a misconfiguration of the melpa package?

**Comment by dominikh** [comment]
When installing from MELPA, you don't really have to do anything. You could `(require 'go-mode)`, but as is, it should be automatically loaded when you open a Go file, anyway.

We should, however, update the docs for the manual install process, now that we no longer include the go-mode-autoloads.el file

**Comment by pmatos** [comment]
@dominikh You are correct. `require` line is not necessary and without it all works fine. I will leave the bug open since you repurposed it.

**Comment by ann-kilzer** [comment]
I'm interested in this, as I'm not finding the go-lang package in the MELPA (stable or otherwise) repo.

**Comment by ann-kilzer** [comment]
I wrote a documentation fix for this. Can you please add me as a collaborator so I can push my changes?

**Comment by dominikh** [comment]
Resolved by b234d71e1adf6fe662435ad869b76a854a2f21f0
