### ISSUE TITLE
pledgie link is broken

### ISSUE THREAD

**Issue by gpaul** [dominikh/go-mode.el#224]
The pledgie link http://pledgie.com/campaigns/21377 in the README seems broken

**Comment by dominikh** [comment]
The entirety of http://pledgie.com being broken might be the cause of that. I'll soon remove/replace the Pledgie link, but I hope that I can get access to the Pledgie's statistics in the meantime, to mention previous support.

Thanks for letting me know.

**Comment by gpaul** [comment]
Lol classic
