### ISSUE TITLE
Provide go tools install / update functionality

### ISSUE THREAD

**Issue by the42** [dominikh/go-mode.el#229]
Enhancement request

go-mode (and go-guru) depend on a series of external tools. For the go-mode experience it would be helpful to provide a command which calls a series of `go install -u` commands to assure required commands are up to date.

As `dep` is round the corner, go-mode might use this tool if a series of supported versions is required to be targeted

(sure, it's a no-brainer to have a shell script with the required go gets inside, especially as a user might prefer `goimports` over `gofmt` )

**Comment by dominikh** [comment]
Vim-style installing of required tools is not something I want to implement. It isn't easy to get right on account of different setups (multiple GOPATH entries, GOPATH entries changing between projects) and not generally knowing where these tools should go. It is much more straightforward to tell users to install the modest amount of external tools currently needed.

A future rewrite of go-mode, backed by a single Go process, will further reduce the number of required tools to one.
