### ISSUE TITLE
go-import-add is very slow

### ISSUE THREAD

**Issue by ageekymonk** [dominikh/go-mode.el#230]
go-import-add when triggered is very slow as it scans through a lots of directories. Is it possible to cache the previous results for faster response?

**Comment by juergenhoetzel** [comment]
I'm using a custom `go-packages-function` function: [go-find-external](https://gist.github.com/juergenhoetzel/8107a01039df08ea3f1c208494ddd7bf) 

It uses the external `GNU find` command to index the packages. On  my system it's 4 times faster than `go-packages-native`

**Comment by ageekymonk** [comment]
Thanks @juergenhoetzel

**Comment by dominikh** [comment]
> go-import-add when triggered is very slow as it scans through a lots of directories. Is it possible to cache the previous results for faster response?

In the common case, your operating system will cache these file system accesses and speed up consecutive runs. Unless you're severely memory constrained, these cached entries will likely persist for your entire development session.

In a future, process-backed rewrite of go-mode, we will look into forms of caching. For the current version of go-mode, caching isn't viable. We would need a way to invalidate the cache, and I am not inclined to look into file system monitoring in pure elisp.

**Comment by psanford** [comment]
In #299 we deprecated `(go-packages-native)` and switched go-import-add to use `(go-packages-go-list)` by default. This is much faster for go modules than it was for GOPATH projects. 

As people switch to modules they will get this speedup.
