### ISSUE TITLE
Prepare for Modules (vgo support)

### ISSUE THREAD

**Issue by the42** [dominikh/go-mode.el#237]
This is a placeholder ticket to collect the various ideas and implementation steps currently [discussing Golang module support](https://github.com/golang/go/wiki/vgo).

A module is a collection of packages, denoted by a common filesystem root, in which in it's simplest form a file named `go.mod` resides. As a consequence there is no more need of `GOPATH`.

A [proposal](https://github.com/golang/go/issues/24301) and [reference implementation](https://go.googlesource.com/vgo/) are under way.

For the design of `go-mode` a couple of questions come up like shall a future go-mode support both environments of set GOPATH and pure Golang module setups?

**Comment by dominikh** [comment]
> For the design of go-mode a couple of questions come up like shall a future go-mode support both environments of set GOPATH and pure Golang module setups?

Yes, it should.

**Comment by kavirajk** [comment]
any update on this?

**Comment by seagle0128** [comment]
Any update please?

**Comment by psanford** [comment]
go-mode works pretty well for me when using modules. Are there concrete things that aren't working for people right now?

**Comment by dominikh** [comment]
Things that come to mind:

- go-packages-add won't work in a module environment; but it also doesn't work correctly in most GOPATH environments, anymore. I recommend deprecating the function and recommending people use goimports instead.
- we could add a major mode for go.mod files. It should be fairly trivial, needing only a very basic syntax table and simple indentation. 
- We should check go-mode for code that expects a GOPATH. Some I've found so far:
  - go-set-project

**Comment by psanford** [comment]
We've added a new major mode for the go.mod file in 50e15c7f20fb277555e2019e95ff28434bb6dd7a

**Comment by dominikh** [comment]
We've deprecated all GOPATH-related functionality. Building projects using GOPATH is not expected to be supported by Go for much longer. `go-packages-add` should in theory work fine if setting `go-packages-function` to `go-packages-go-list`, but in reality, most people use goimports or gopls, anyway, and don't add imports manually.

go-mode has been working fine with modules for a while, so I think we can close this issue.
