### ISSUE TITLE
How to setup when using "dep" so that it reads /vendor/?

### ISSUE THREAD

**Issue by ZzAntares** [dominikh/go-mode.el#244]
Hello, first of all thanks for the package very easy to setup. However I'm having trouble when using `dep` to manage the dependencies, flycheck reports errors regarding it can't find packages:

```
  cannot find package "github.com/gorilla/mux" in any of:
  /usr/local/Cellar/go/1.10.2/libexec/src/github.com/gorilla/mux (from $GOROOT)
  /Users/antares/go/src/github.com/gorilla/mux (from $GOPATH)
```

I'm guessing this happens because its not looking for packages in the `vendor/` directory generated by `dep`.

- My `$GOPATH` is `/Users/antares/workspace/golang`.
- My project is in `/Users/antares/workspace/golang/src/github.com/ZzAntares/go-rest-api`
- The structure in the `go-rest-api` project is:

```txt
.
├── Gopkg.lock
├── Gopkg.toml
├── src
│   └── main.go
└── vendor
    └── github.com
        └── gorilla
            ├── context
            └── mux
```

I also notice the reported `$GOPATH` in the error message is wrong, it says:

```
  /Users/antares/go/src/github.com/gorilla/mux (from $GOPATH)
```

While in the terminal my `$GOPATH` is:

```
/Users/antares/workspace/golang
```

### What I've tried

I don't know if the intended usage of `go-set-project` is precisely to tell it where to look the packages, but when using that function, then the error message changes to:

```
  cannot find package "github.com/gorilla/mux" in any of:
  /usr/local/Cellar/go/1.10.2/libexec/src/github.com/gorilla/mux (from $GOROOT)
  /Users/antares/workspace/golang/src/github.com/ZzAntares/go-rest-api/src/github.com/gorilla/mux (from $GOPATH)
  /Users/antares/workspace/golang/src/github.com/ZzAntares/go-rest-api/vendor/src/github.com/gorilla/mux
```

Now, its very close to find the package, is looking in:

```
/Users/antares/workspace/golang/src/github.com/ZzAntares/go-rest-api/vendor/src/github.com/gorilla/mux
```

But as you can see by the project structure the package is in:

```
  /Users/antares/workspace/golang/src/github.com/ZzAntares/go-rest-api/vendor/github.com/gorilla/mux
```

Note that `dep` does not generate a `/vendor/src/github.com/` folder but a `/vendor/github.com/` folder.

What is the correct way to setup the correct `$GOPATH` and extra `vendor/` directories?

Thanks in advance for any help!

**Comment by dominikh** [comment]
Odds are this is because you're on OS X, setting your environment variables in .bashrc (or .profile or one of the other shell related startup files), but starting Emacs from the GUI. In that case, Emacs won't inherit any of your shell's environment variables. 

You can either start emacs from a terminal, run `(setenv "GOPATH" "/path/to/your/gopath")` in emacs, or use something like https://github.com/purcell/exec-path-from-shell

Note that the same thing also applies to your PATH variable, which probably should include GOPATH/bin.

**Comment by ZzAntares** [comment]
Yes!, you were right, that was the problem, I added `$GOPATH` and `$GOROOT` to `exec-path-from-shell-variables`:

```elisp
  (dolist (envvar '("GOPATH" "GOROOT"))
    (add-to-list 'exec-path-from-shell-variables envvar))
```

And now is working perfect! Sorry for the issue I assumed that the `exec-path-from-shell` copied all those extra variables.
