### ISSUE TITLE
go-mode.el already a file

### ISSUE THREAD

**Issue by andreas-roehler** [dominikh/go-mode.el#255]
Naming the directory like a file seems suboptimal. Not a big issue though.

**Comment by thiderman** [comment]
That's a pretty common pattern when naming projects for emacs packages. Does this cause any trouble for you?

**Comment by andreas-roehler** [comment]
On 17.08.2018 09:39, Lowe Thiderman wrote:
> That's a pretty common pattern when naming projects for emacs packages. 
> Does this cause any trouble for you?
> 
It took some seconds. Not really a big thing. But it took seconds for 
nothing.

**Comment by andreas-roehler** [comment]
http://lists.gnu.org/archive/html/help-gnu-emacs/2018-08/msg00084.html

**Comment by dominikh** [comment]
I'm not going to rename a widely used project because of a bug in GNU Emacs that virtually nobody runs into. Updating all the references and package repositories would have a much greater negative impact.

I'll keep it in mind for future projects, though.
