### ISSUE TITLE
Provide a go-install function

### ISSUE THREAD

**Issue by lawrsp** [dominikh/go-mode.el#257]
Some tools (such as  gocode..)  use pkg files to work
provide a install function would make these tools works better.

I tried to write some code in spacemacs layer and used a while for my own, I think it is not bad.
After some discusses about the functionality in the PR I submit to spacemacs, I rechecked and now I think it is better to do it in go-mode package. So it could prevent conflict with gofmt, show more error messages with the same format as gofmt, etc.

How do you think ?

BTW,
vscode added go install, go build functions Microsoft/vscode-go#287
golang team has a [plugin form sublime](https://github.com/golang/sublime-build)

**Comment by muirrn** [comment]
Thank you for the suggestion. gocode and friends will soon be replaced by gopls. gopls uses only the source code, so `go install` is not necessary. gopls also supports diagnostics/linting. Closing as I don't think running "go install" from go-mode will be useful in general going forward.
