### ISSUE TITLE
M-x godoc-at-point causes error on latest godoc

### ISSUE THREAD

**Issue by buzztaiki** [dominikh/go-mode.el#262]
I got following error in `*Messages* buffer when run `M-x godoc-at-point`

```
godoc: Unexpected arguments.
usage: godoc -http=localhost:6060
  -analysis string
    	comma-separated list of analyses to perform (supported: type, pointer). See http://golang.org/lib/godoc/analysis/help.html
  -goroot string
    	Go root directory (default "/usr/lib/go")
  -http string
    	HTTP service address (default "localhost:6060")
  -index
    	enable search index
  -index_files string
    	glob pattern specifying index files; if not empty, the index is read from these files in sorted order
  -index_interval duration
    	interval of indexing; 0 for default (5m), negative to only index once at startup
  -index_throttle float
    	index throttle value; 0.0 = no time allocated, 1.0 = full throttle (default 0.75)
  -links
    	link identifiers to their declarations (default true)
  -maxresults int
    	maximum number of full text search results shown (default 10000)
  -notes string
    	regular expression matching note markers to show (default "BUG")
  -play
    	enable playground
  -templates string
    	load templates/JS/CSS from disk in this directory
  -timestamps
    	show timestamps with directory listings
  -url string
    	print HTML for named URL
  -v	verbose mode
  -write_index
    	write index to a file; the file name must be specified with -index_files
  -zip string
    	zip file providing the file system to serve; disabled if empty
```

**Comment by buzztaiki** [comment]
I think that this error occurred because cli support was deleted.

see https://github.com/golang/go/issues/25443

**Comment by buzztaiki** [comment]
`M-x godoc` seems to be working properly for me.

**Comment by dominikh** [comment]
Short-term solution: set the godoc-at-point-function variable to godoc-gogetdoc (and install [gogetdoc](https://github.com/zmb3/gogetdoc)). In the long term that'll likely be the only option we support.

**Comment by buzztaiki** [comment]
Thank you! gogetdoc works fine!

**Comment by yanyuzhy** [comment]
I guess you are using go 1.11+, and the default value of  “godoc-and-godef-command”  is "godoc"，how ever the right command value is "go doc".

Here is the source code in go-mode.el
```el
(defcustom godoc-and-godef-command "godoc"
  "Which executable to use for `godoc' in `godoc-and-godef-command'.
Must be 'godoc' and not 'go doc' and can be an absolute path or
an executable in PATH."
  :type 'string
  :group 'go)
```

So you should set it to "go doc" to fix the problem.
 ```el
 (setq godoc-and-godef-command "go doc")
```
You should set it in dotspacemacs/user-config function  if you are using spacemacs.

I have tried this, and it works for me!

**Comment by psanford** [comment]
@dominikh do you remember why the documentation says godoc-and-godef-command must be 'godoc' and not 'go doc'? Looks like this was intentionally split to use 'go doc' for the normal (godoc) and to keep using 'godoc' for (godoc-at-point): https://github.com/dominikh/go-mode.el/commit/205672ff1f4e5637fc5613e9304a1cecc35df254.

**Comment by psanford** [comment]
It looks like 'go doc' works for at least some cases, like if you are on a struct name or a package level function. 

In any case it seems like we should switch the default value to something besides 'godoc' as that no longer provides any cli output.

**Comment by dominikh** [comment]
Judging by #127, `go doc` didn't always support specifying file system paths to packages. Apparently this works now.
