### ISSUE TITLE
Does not indent function blocks correctly

### ISSUE THREAD

**Issue by jjzmajic** [dominikh/go-mode.el#275]
If I type (`|` represents cursor):
```
func foo() {|}
```
and then hit `<return>`,  the new line is not indented at all and the following happens if I keep typing:
```
func foo() {
bar()
}
```
After calling `gofmt` it is indented correctly to this:
```
func foo() {
    bar()
}
```
I checked, `<return>` is calling `newline-and-indent`, which is in turn calling `go-mode-indent-line`.

**Comment by jjzmajic** [comment]
I just discovered this is due to iterference with `clean-aindent-mode`. However, the issue only happens with go mode, and not, for example with C (or any other mode I'm using, so I'll keep it open for now in case it's an idiosyncrasy that can be addressed.

For now, my workaround is simply ` (add-hook 'go-mode-hook (lambda () (clean-aindent-mode -1)))`

**Comment by psanford** [comment]
It doesn't sound like this is a bug in go-mode so I'm going to close this issue. Feel free to reopen if you disagree.
