### ISSUE TITLE
gofmt doesn't work on windows

### ISSUE THREAD

**Issue by demas** [dominikh/go-mode.el#276]
On Windows `gofmt` write to the Messages buffer:

```
Wrote c:/Users/andre/AppData/Local/Temp/gofmtXYhFv6.go
Calling gofmt: gofmt (-w c:/Users/andre/AppData/Local/Temp/gofmtXYhFv6.go)
Applied gofmt
```
But the code remain unformatted.

I am trying to debug: `gofmt` created temporary file -> launch `gofmt` -> the temporary file was correctly (!) formatted -> temporary file was deleted, but original file remain the same.

Looks like the code in temporary file was formatted correctly, but original file/buffer was not updated.

**Comment by dominikh** [comment]
I'm afraid you'll have to do your own debugging on this one. I don't use Windows, and as far as I am aware, other users of go-mode.el on Windows do not suffer from this problem.

The only thing that comes to mind immediately is the fact that go-mode.el depends on the `diff` utility to apply the changes gofmt made. Make sure `diff` is available and in PATH.

**Comment by demas** [comment]
Thanks. I have `diff` installed. I am afraid my knowledge of emacs is not enough to debug and fix the error. But thank you for your answer.

**Comment by psanford** [comment]
It doesn't sound like this is an issue with go-mode so I'm going to close this. Feel free to reopen if you disagree.

**Comment by bradyt** [comment]
From https://github.com/bradyt/dart-server/blob/master/README.md#general-configuration.

> If you're on Windows, you will need to make sure that the diff executable is available to Emacs. One way to do this is install from http://gnuwin32.sourceforge.net/packages/diffutils.htm and add something like the following to your init file. `(setq exec-path (append exec-path '("C:/Program Files (x86)/GnuWin32/bin")))`

From https://github.com/bradyt/dart-mode/wiki/Formatting#ensure-diff-is-available.

``` org
** Ensure =diff= is available

Especially on Windows, you may have to add =diff= to your system and
=PATH=.

One way to do this is install from
[[http://gnuwin32.sourceforge.net/packages/diffutils.htm]] and add
something like the following to your init file. 

#+BEGIN_SRC elisp
(setq exec-path (append exec-path '("C:/Program Files (x86)/GnuWin32/bin")))
#+END_SRC

On Windows, you may find this all easier via chocolatey, which is
anyways apparently a recommended method to install =dart= on Windows.
```
