### ISSUE TITLE
Add godef-jump to evil-jump list?

### ISSUE THREAD

**Issue by dvcrn** [dominikh/go-mode.el#277]
Hi, I wonder if I can setup `godef-jump` to add to the evil jump list before jumping, so that it becomes possible to jump back to the previous location with `C-o` or `evil-jump-backward`. 

Ref: https://github.com/dominikh/go-mode.el/issues/112

Any ideas?

**Comment by dominikh** [comment]
This is probably best asked the evil people. 

godef-jump is calling `xref-push-marker-stack` on versions of Emacs that use XRef. On older versions of Emacs, we manually add to `find-tag-marker-ring`. This mimics the behaviour of Emacs builtins that jump to things. 

If evil can't be made to work with those, then you'll probably have to [advise](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) godef-jump to add to evil's own data structures. In either case I cannot tell you how evil works, I have never used it.

**Comment by scsmithr** [comment]
`(evil-add-command-properties #'godef-jump :jump t)` should get you what you want.
