### ISSUE TITLE
godef-jump fails with "There must be at least one package that contains the file"

### ISSUE THREAD

**Issue by federicotdn** [dominikh/go-mode.el#286]
I've been trying to get `godef-jump` to work on a project I've been developing on. The project uses Go modules, and is outside `GOPATH`.

When I use `godef-jump` on, say, a call to `flag.StringVar`, a new empty buffer appears named "godef: There must be at least one package that contains the file" ([maybe related](https://github.com/rogpeppe/godef/blob/master/packages.go#L32)). I've traced the problem back to the `godef--call` function on `go-mode.el`. When `call-process-region` invokes `godef`, the parameters it passes to it are correct, but for some reason `godef` exits with an error. I have tried calling `godef` on a terminal with the *exact same* arguments and it works perfectly well:
```bash
$ godef -f /home/fede/project/main.go -o 6976 -t -i < /home/fede/project/main.go
/snap/go/4098/src/flag/flag.go:758:6
StringVar func(p *string, name string, value string, usage string)
```
I'm not sure what's going on.

(Slightly related: why is the `godef` `-f <file>` flag being used if the contents of the file are already being fed into it via stdin?)

**Comment by psanford** [comment]
If the same command is working from the command line then the first thing that is worth checking is if there are any environment variables that are different between your interactive shell and your emacs process. Depending on how you are launching emacs it is possible it doesn't have everything your interactive shell environment has (or it has different values).

**Comment by federicotdn** [comment]
I think it's something related to buffers visiting `.go` files. If I try this in IELM, it works correctly:
```elisp
(call-process "godef" nil (get-buffer-create "foobar") nil "-t" "-o" "6976" "-f" "/home/fede/project/main.go")
```

The buffer `foobar` then contains:
```
/snap/go/4098/src/flag/flag.go:758:6
StringVar func(p *string, name string, value string, usage string)
```

But if I visit `main.go` and do <kbd>M-x</kbd> `eval-expression` and paste the previous Elisp code, the `foobar` buffer ends up with:
```
godef: There must be at least one package that contains the file
```

**Comment by federicotdn** [comment]
It appeared to be something related to `default-directory`. Evaluating the following code solved the issue for me:
```elisp
(advice-add 'godef--call :around
	    (lambda (fn &rest args)
	      (let ((default-directory "~"))
		(apply fn args))))
```

**Comment by psanford** [comment]
Hmm, strange. `(file-truename)` will expand the filename using `default-directory` if the path isn't absolute. When I'm in a go buffer backed by a file and eval `(buffer-file-name (go--coverage-origin-buffer))` I get an absolute path to the file. Is that what you get?

**Comment by federicotdn** [comment]
Evaluating that results in an absolute path here as well: "/home/fede/project/main.go"

**Comment by federicotdn** [comment]
Even stranger, printing the value of `(file-truename (buffer-file-name (go--coverage-origin-buffer)))` inside `godef--call` always results in the correct absolute path, with or without `advice-add`, so I'm not sure why that worked. Maybe something inside `call-process-region`?

**Comment by federicotdn** [comment]
This works:
```elisp
(let ((default-directory "~"))  ;; Or any other directory
  (call-process "godef"
		nil
		(get-buffer-create "foobar")
		nil
		"-t"
		"-o" "6976"
		"-f" "/home/fede/project/main.go"))
```

But this doesn't:
```elisp
(let ((default-directory "~/project"))  ;; Directory containing main.go
  (call-process "godef"
		nil
		(get-buffer-create "foobar")
		nil
		"-t"
		"-o" "6976"
		"-f" "/home/fede/project/main.go"))
```
