### ISSUE TITLE
Consider changing the go-packages-function default to 'go-packages-go-list (and what to do about go-package-native)

### ISSUE THREAD

**Issue by psanford** [dominikh/go-mode.el#298]
The current default for 'go-packages-function is 'go-packages-native. Based on the variable documentation, I think the rationale for that was that go-packages-go-list was historically slower than go-packages-native for many environments. 

Modules seem to change the equation. At least in my environment when I'm working in a module project, go-packages-native is painfully slow compared to go-packages-go-list. I think part of this is there is a lot more stuff that the go tool has been sticking in $GOPATH/pkg in recent releases that we aren't currently skipping. There can now also be multiple versions of packages in there due to modules. 

I also think that `go list` is probably faster for modules than it used to be for GOPATH packages as now it can cull packages that are not in go.mod dependencies. 

Another issue with go-packages-native is it doesn't understand the module pathnames under pkg. So for example it includes the following incorrect package name for me right now:  

```
golang.org/x/tools@v0.0.0-20190213223815-88f95592de8c/go/gccgoexportdata/testdata/long
```

I think it makes sense to switch the default 'go-packages-function to 'go-packages-go-list and to mark go-packages-native as deprecated.

**Comment by dominikh** [comment]
I agree. I'd go as far as to say that go-package-native is plain broken. It was a good idea when GOPATH was all we had, people putting other stuff in $GOPATH/pkg made it slower, the Go build cache broke it slightly, and modules break it a lot. The only way go-package-native could work correctly nowadays is if we implemented a lot of `go list`'s logic in elisp. And we really shouldn't do that.

go-packages as a whole isn't very relevant nowadays, anyway. Its main use is for go-import-add, and the majority of people use goimports for that now, and will use LSP eventually. Switching to the slower but correct go-packages-go-list should be fine.

> I think the rationale for that was that go-packages-go-list was historically slower than go-packages-native for many environments

That is indeed why go-packages-native was added. It was at least an order of magnitude faster.
