### ISSUE TITLE
Cannot find import using golang 1.13

### ISSUE THREAD

**Issue by aixi2494** [dominikh/go-mode.el#300]
use go get -u github.com/kataras/iris 
in emacs go-import-add not find iris

No .a file found in gopath/pkg

Ask how to generate a .a file.

--------------------------------------------------
or
go-import-add can find iris

**Comment by psanford** [comment]
Are you using modules or gopath? Does it work if you `(setq go-packages-function 'go-packages-go-list)`?

Take a look at https://github.com/dominikh/go-mode.el/issues/298 for some context. There are two underlying functions that go-import-add can use to determine the set of available packages. The current default for this is `(go-packages-native)` which tries to determine the packages available just in elisp by looking at your $GOPATH/pkg directory. This strategy has been working less and less well with recent Go releases. `(go-packages-go-list)` should work correctly although it may be slower if you are still in GOPATH mode.

There's a PR to switch the default to go-packages-go-list that should be merged soon.

**Comment by aixi2494** [comment]
It’s my fault, I don’t know how to use mod.

**Comment by aixi2494** [comment]
After learning to use mod, great
