### ISSUE TITLE
[Feature Request]add more highlight support

### ISSUE THREAD

**Issue by taigacute** [dominikh/go-mode.el#306]
hi  a vimer new come to emacs , vim-go provide lots of highlight group, so i want know does go-mode support it? like this pic,vim-go support the operators highlight and some others group.
![image](https://user-images.githubusercontent.com/41671631/66255474-548b7300-e7b6-11e9-812b-c98d107b15fe.png)

**Comment by psanford** [comment]
I don't think coloring operators is very common in emacs language modes. The default list of font-lock faces doesn't have one specifically for operators: https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html.

Go mode currently attempts to handle the following cases:
- font-lock-builtin-face
- font-lock-constant-face
- font-lock-function-name-face
- font-lock-keyword-face
- font-lock-type-face
- font-lock-string-face
- font-lock-comment-face

There are a few known issues where we are not properly fontifying certain things that we'd like to fix (#256 and #21). I don't think it is likely the we would add non-standard fontification for things like operators though.

**Comment by muirrn** [comment]
@taigacute if you want to font lock operators/punctuation yourself you can start with config like this:

```elisp
(defface my-font-lock-operator-face
  `((t (:foreground "yellow"))) ;; change to desired color
  "Face for operators.")

(font-lock-add-keywords 'go-mode
  ;; change to desired operator regex
  '(("[&^|!<>:=,+*/%-]" 0 'my-font-lock-operator-face)))
```

You need to rerun `go-mode` after evaluating the above code for it to take effect in existing buffers.

**Comment by taigacute** [comment]
@muirrn   thanks i will try it.

**Comment by taigacute** [comment]
I want know why doesnt support highlight the type which in interface or struct .like 
```go
type A struct{
        name   string <---highlight string??
}
```

**Comment by psanford** [comment]
Thats #256. We have some plans to fix that we just haven't gotten around to it yet.

**Comment by taigacute** [comment]
@psanford  i  found you define this `go-mode-keywords`, so i want know  can I change the keyword color?

**Comment by taigacute** [comment]
hi any update?

**Comment by psanford** [comment]
Most people use a color theme to customize the colors used across all modes. If you don't want to do that you can run `M-x customize-face font-lock-keyword-face` to set a different color for just the keyword face.

**Comment by taigacute** [comment]
hmm I used a stupid way.. now it looks like this pic , what do you think?

![image](https://user-images.githubusercontent.com/41671631/66654559-10441b00-ec6d-11e9-84bb-d52761689759.png)
