### ISSUE TITLE
issues with go-playground: ‘search failed: “\n\n” 

### ISSUE THREAD

**Issue by 7l-l04** [dominikh/go-mode.el#316]
Does go-play require some setup? I’m finding that when I try to run any of go-play-buffer, go-play-region, go-download-play, I get the following error:

```
ERROR IN PROCESS SENTINEL: search failed: “

“
```

**Comment by psanford** [comment]
It should work without any additional setup.

It looks like its not connecting to https://play.golang.org/. Does your emacs have gnutls enabled? What does `C-h v system-configuration-features` show for you?

**Comment by thor314** [comment]
Its value is
"XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETT\INGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT \LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYST\EMD LCMS2"

I checked whether I have gnutls installed, and it appears I do. I’m unsure what you mean by enabled. As in, have I set gnutls somewhere in my init script? I haven’t.

**Comment by psanford** [comment]
I meant is your emacs built with GNUTLS support turned on? Looks like it is. 

Try this to see what the response emacs is getting: 

`M-: (switch-to-buffer (url-retrieve-synchronously "https://play.golang.org/p/HmnNoBf0p1z"))`

**Comment by thor314** [comment]
M-: is undefined, (but ooh that looks like a useful, what is it?) I put this in scratch and called `M-x eval-defun`, I got this:
```
Debugger entered--Lisp error: (void-function url-retreive-synchronously)                                          (url-retreive-synchronously "https://play.golang.org/p/HmnNoBf0p1z")                                            (switch-to-buffer (url-retreive-synchronously "https://play.golang.org/p/HmnNoBf0p1z"))                         eval-region(146 233 t #f(compiled-function (ignore) #<bytecode 0xd8da77>))  ; Reading at buffer position 146    elisp--eval-defun()                                                                                             eval-defun(nil)                                                                                                 funcall-interactively(eval-defun nil)                                                                           call-interactively(eval-defun record nil)                                                                       command-execute(eval-defun record)                                                                              execute-extended-command(nil "eval-defun" "eval-def")                                                           funcall-interactively(execute-extended-command nil "eval-defun" "eval-def")                                     call-interactively(execute-extended-command nil nil)                                                            command-execute(execute-extended-command)
```

**Comment by psanford** [comment]
You may need to `(require 'url)` although if you've already loaded go-mode that should already be there.

What version of emacs are you using?

**Comment by psanford** [comment]
I'm going to close out this issue since there hasn't been any updates for a few months.
