### ISSUE TITLE
godoc-at-point fails on package names

### ISSUE THREAD

**Issue by sfllaw** [dominikh/go-mode.el#323]
With `GO111MODULE=on`, `godoc-at-point` is unable to resolve `os`:
``` go
package main

import "os"

func main() {
	os.Exit(0)
//	^ call godoc-at-point here
}
```

with the following message: `godoc: doc: invalid identifier "import"`

I believe this is because `(godef--call (point))` returns the following message:
```
("main.go:6:2" "import (os \"os\")" "")
```

This is documented as being unhandled by `godoc-and-godef`, but it should be relatively easy to change if the following code was able to parse the `import` statement for the third result, _i.e._ the full package name:
https://github.com/dominikh/go-mode.el/blob/cad6d0a522f8f5c351a1332bcd54bd5ffd8ce30d/go-mode.el#L276-L278

**Comment by sfllaw** [comment]
Here’s a version that works for me:
``` elisp
(defun godoc-and-godef (point)
  "Use a combination of godef and godoc to guess the documentation at POINT.

Due to a limitation in godoc, it is not possible to differentiate
between functions and methods, which may cause `godoc-at-point'
to display more documentation than desired.  Furthermore, it
doesn't work on package names or variables.

Consider using ‘godoc-gogetdoc’ instead for more accurate results."
  (condition-case nil
      (let* ((output (godef--call point))
             (file (car output))
             (name-parts (split-string (cadr output) " "))
             (first (car name-parts)))
        (if (not (godef--successful-p file))
            (message "%s" (godef--error file))
          (go--godoc
           (if (string= first "import")
               (let ((pkg-name (string-remove-suffix ")" (caddr name-parts))))
                 (car (split-string-and-unquote)))
             (format "%s %s"
                     (file-name-directory file)
                     (if (or (string= first "type") (string= first "const"))
                         (cadr name-parts)
                       (car name-parts))))
           godoc-and-godef-command)))
    (file-error (message "Could not run godef binary"))))```

**Comment by psanford** [comment]
Can you send a PR for your fix?

**Comment by sfllaw** [comment]
@psanford Any chance you could look at #329, #330, and #331?

**Comment by sfllaw** [comment]
@psanford Just a friendly ping to look at #329, #330, and #331 please?

**Comment by sfllaw** [comment]
@psanford Ping? Please review #329, #330, and #331?

**Comment by sfllaw** [comment]
@psanford I have sent in a fix as requested, is there something you would like me to revise?

**Comment by sfllaw** [comment]
@psanford Should we give up on the associated pull requests since gopls will obsolete godoc?

**Comment by dominikh** [comment]
Sorry for the lack of response. I do think we should drop these changes in favour of relying on gopls. I don't feel confident in the added parsing required to make #329 and #330 work, and I don't think it benefits enough people to risk breaking things.
