### ISSUE TITLE
Support rename by gopls

### ISSUE THREAD

**Issue by on99** [dominikh/go-mode.el#338]
gopls already supports renaming https://go-review.googlesource.com/c/tools/+/182585/

gorename failed to rename a variable/function/etc since gorename does not work with go modules, consider switching to gopls for renaming.

**Comment by psanford** [comment]
I think our general assumption is that you will use lsp-mode or eglot to interact with gopls. I suppose we could support the cli rename command in go-mode.

**Comment by dominikh** [comment]
I'd rather not see us shell out to the `gopls` CLI. People should indeed use lsp-mode (or similar).

Also, wasn't goimports updated to support modules a while ago?

**Comment by on99** [comment]
Got it, thank you!
