### ISSUE TITLE
`go-remove-unused-imports` cannot operate on unsaved buffer

### ISSUE THREAD

**Issue by admacro** [dominikh/go-mode.el#340]
Hi, I want to **format and remove** unnecessary imports when saving go buffers, so I wrote this little function to do it. However, I got an error saying "`go-remove-unused-imports` cannot operate on unsaved buffer". 
```
(defun go-tidy-up ()
  (gofmt-before-save)
  (go-remove-unused-imports))
(add-hook 'before-save-hook 'go-tidy-up)
```
Error message
```
Calling gofmt: gofmt (-s -w /var/folders/z6/f1935z3x7wq9bwbfvfmnq5xw0000gn/T/gofmtwP3cch.go)
Applied gofmt
Error: (wrong-number-of-arguments #[(arg) "\212p\306\211\307\303!\203\303\310!\210\311\306\312\"\210\313 \203$\314\315!\210\202Y\316 \211\306\211\203R
@\317!\210\320 \210\203H\321\322 \323 \"\210\202K\324 \210
A\211\204/*\314\325G\"\210	\205`\303\326!,\207" [lines flymake-state cur-buffer flymake-mode import --dolist-tail-- nil boundp -1 save-some-buffers #[nil "p\232\207" [cur-buffer] 2] buffer-modified-p message "Cannot operate on unsaved buffer" go-unused-imports-lines go--goto-line beginning-of-line comment-region line-beginning-position line-end-position go--delete-whole-line "Removed %d imports" 1 arg] 4 ("/Users/james/.emacs.d/elpa/go-mode-20200112.2140/go-mode.elc" . 61594) "P"] 0)

```

How can I make it work on unsaved buffers?

**Comment by muirdm** [comment]
`go-remove-unused-imports` is implemented by running `go build` or `go test`, so it isn't easy to make it work on unsaved buffers. If you install `goimports` and set `gofmt-command` to "goimports" then `(gofmt-before-save)` will handle imports as well and you no longer need `go-remove-unused-imports`.

Alternatively you can use lsp-mode and gopls and then use `(lsp-organize-imports)` to add/remove imports automatically. This will be the fastest and best long term approach, but requires some setup.

**Comment by admacro** [comment]
Hi muirdm, I do use lsp-mode with go, so I tried both methods. Both worked with the same effect. Thank you for suggesting the `lsp-organize-imports` command. It also does code formatting. One problem is now I can't make `gofmt` to simplify code (`-s`) on save. I searched around and found this related issue ([golang issue#8759](https://github.com/golang/go/issues/8759)) to which there is no solution for now.

Here is the configuration.
```
;; The goimports approach
(setq gofmt-command "goimports") 
(add-hook 'before-save-hook 'gofmt-before-save)
```
or
```
;; The lsp approach
(add-hook 'before-save-hook 'lsp-organize-imports)
```

**Comment by muirdm** [comment]
Great! Note that in new versions of gopls `lsp-organize-imports` does not format the buffer (you need to also call `lsp-format-buffer`). [Here](https://github.com/golang/go/issues/37221) is an issue for adding `-s` support to gopls.

**Comment by admacro** [comment]
Ah! Thanks again for the info. I just updated `lsp-mode` and add `lsp-format-buffer` to my config. 😃 

```
;; the lsp approach
(add-hook 'before-save-hook
          (lambda ()
            (lsp-format-buffer)
            (lsp-organize-imports)))
```
