### ISSUE TITLE
godoc to behave more like apropos-library

### ISSUE THREAD

**Issue by microamp** [dominikh/go-mode.el#341]
It would be awesome if `godoc` (with `godoc-use-completing-read` set to `t`) behaved more like `apropos-library` (see below).

First, select a library, in this case, `tramp`.

![2020-02-24-171052_1265x704_scrot](https://user-images.githubusercontent.com/1378791/75128411-d01b9b80-5728-11ea-90f2-9982b191ca61.png)

Choose a function called `copy-tramp-file-name` 

![2020-02-24-171111_1265x704_scrot](https://user-images.githubusercontent.com/1378791/75128422-d6aa1300-5728-11ea-9364-bfb6b325a5f0.png)

Pressing `q` will redirect the user back to the main `tramp` page.

Currently, our buffer looks like this (i.e. the output of `go doc <lib>`, in this case `go doc json`).

![2020-02-24-171850_1264x704_scrot](https://user-images.githubusercontent.com/1378791/75128649-01489b80-572a-11ea-8953-0d9e6f05310c.png)

There's currently no shortcut to select and view a specific type/function/etc. from this buffer. e.g. `go doc json.Marshal`

**Comment by microamp** [comment]
Related: https://github.com/golang/go/issues/34293

**Comment by psanford** [comment]
Thanks for opening this issue. I don't think the current maintainers have much bandwidth to implement this feature request. If someone really wants this I would suggest first implementing it as a separate package. That would allow people to start testing and using it immediately without first having to go through a full code review. Then we could have a discussion of if it makes more sense for the code to remain in a separate package or get integrated into the existing go-mode godoc functions.

I'm going to close this issue for now. Please let us know if you do implement this in a separate package so people can try it out.
