### ISSUE TITLE
does godef-jump work since the go1.14 update?

### ISSUE THREAD

**Issue by bastien-seqone** [dominikh/go-mode.el#342]
Since the go 1.14 update, i have a very strange behavior : when i call godef-jump on a function, the file open is like : "/currentpath/2020/02/28 09" because of the day date (09 is the hour, i guess).

The installed version is 20200112.2140

Is it a bug or do I have a problem on my side?

Otherwise, thank you for this package, I use it every day!

Have a nice day,

**Comment by psanford** [comment]
That doesn't sound like a go-mode issue. Maybe its an issue with the version of godef you have installed. I have two suggestions for you:

1) Switch to using gopls and lsp-mode. Tools like godef/gocode/guru are deprecated and will probably stop working all together at some point in the future. gopls is now the best option for code navigation/code completion/type inspection. There's a good example starting config here: https://github.com/golang/tools/blob/master/gopls/doc/emacs.md

2) If you absolutely refuse to use gopls try recompiling godef with 1.14. If it still doesn't work try running godef from the command line and see if that work. But really you will be much better off in the long run to switch over to using gopls and lsp-mode.

**Comment by bastien-seqone** [comment]
Thank's you very much, i will try to use gopls - which I'm already using in part. I think my configuration is not very consistent :)

**Comment by bastien-seqone** [comment]
All worked perfectly. Thank's you again, and sorry for the inconvenience.
