### ISSUE TITLE
Indenting problem for map or slice variable define: var foo = map[int] int {

### ISSUE THREAD

**Issue by netjune** [dominikh/go-mode.el#344]
For example:
```
var foo = map[int]int {
    1:1,
        2:2,
        3:3,
}
```

And if I delete a whitespace in the first line (the whitespce before '{'), then it is indented like this:
```
var foo = map[int]int{
    1:1,
    2:2,
    3:3,
}
```

**Comment by muirdm** [comment]
Why is there a space there?

We use the lack of whitespace to tell the difference between a composite literal curly and a function curly. I don't think there is much value in trying to fix this because gofmt removes the space and normally one doesn't put a space there.

**Comment by netjune** [comment]
Then no problem since it is expected.
Thanks.
