### ISSUE TITLE
Continuation lines for function calls get extra indentation

### ISSUE THREAD

**Issue by evanmoses-okta** [dominikh/go-mode.el#346]
With fluent-style function calls we might have many-line continuations with chained function calls.  `go-mode` is adding an additional indent level after every line.

Go-mode's actual formatting:

```
func Test() {
	foo := Bar().
		Baz().
                        Quxx().
                                Another()
}
```

Expected (gofmt):

```
	foo := Bar().
		Baz().
		Quxx().
		Another()
```

**Comment by muirdm** [comment]
Thanks for the report! Can you make sure it's fixed for you by above change?

**Comment by evanmoses-okta** [comment]
@muirdm it works! Thanks for fixing.
