### ISSUE TITLE
"old-style backquotes detected" breaks go-mode in emacs 27

### ISSUE THREAD

**Issue by jmartin84** [dominikh/go-mode.el#349]
Updating go-mode from elpa today introduced a breaking change for emacs 27 with the error
> File mode specification error: (error Loading ‘~/.emacs.d/elpa/go-mode-20200330.1654/go-mode.el’: old-style backquotes detected!)

I managed to trace the issue to line 1016 in `go-mode.el`. 

`(, 0) ; loose binding expression separator`

The change was introduced in this commit. 
https://github.com/dominikh/go-mode.el/commit/c9f5e9289529eefdaa5c6e987e0e7e923777a2ae

I'm not really sure how to fix it, but I'd be happy to submit a pr for it if someone could give me some guidance.

Thanks!

**Comment by muirdm** [comment]
Oops. If you escape it to `(\, 0)` does that fix it?

**Comment by yuezhu** [comment]
I have encountered the same issue, and that could fix:

> Oops. If you escape it to `(\, 0)` does that fix it?
