### ISSUE TITLE
Fail to setq gofmt-args

### ISSUE THREAD

**Issue by alisonjoe** [dominikh/go-mode.el#365]
(setq gofmt-command "goimports")
(setq gofmt-args "-local github.com")

my project need use goimports -local xxx.com, but i execute fail.

this is errmsg, pls

Calling gofmt: goimports (-srcdir GOPATH/sayhello_test.go 45 108 111 99 97 108 32 103 105 116 104 117 98 46 99 111 109 -w apply: Wrong type argument: stringp, 45

It looks like it's automatically converted to ASCII

**Comment by muirdm** [comment]
I think `gofmt-args` is a list. Can you try again with `(setq gofmt-args '("-local" "github.com"))`?

**Comment by alisonjoe** [comment]
> I think `gofmt-args` is a list. Can you try again with `(setq gofmt-args '("-local" "github.com"))`?

I'm not very familiar with elisp programming. yes, The way you said it worked 

thx!!!

**Comment by psanford** [comment]
Maybe we should tweak the docs for `'gofmt-args` or maybe change its default from nil to be an empty list.
