### ISSUE TITLE
Incorrect multiline comment indentation

### ISSUE THREAD

**Issue by Murgalha** [dominikh/go-mode.el#369]
I recently started using this mode and noticed the multiline comments do not keep the correct indentation. I don't have enough elisp experience to go thourgh the code and fix it myself, so any help would be appreciated. Thanks in advance.

![image](https://user-images.githubusercontent.com/23103524/92812776-46ff4580-f396-11ea-8dad-6521678f4503.png)

Note this is also an incorrect behavior according to `gofmt`.

**Comment by muirdm** [comment]
@Murgalha can you try the above change and see if it works as you expect?

**Comment by Murgalha** [comment]
I tested the change and yes, it is working, but the alignment column of the comment differs from the one used in `gofmt` (Your code aligns with the first character column, and `gofmt` aligns with the beginning `/`, but I guess I'm nitpicking here), which does not bother me, just pointing it out. I also noticed the `electric-indent-mode` only triggers indentation when the comment in that line begins at column 0. 
As a side note, `gofmt` has a really strange behavior when dealing with this type of comment, so I really don't know what the "standard" is.
Aside from those points, yes, the overall behavior is the one expected, it is now indenting.

**Comment by muirdm** [comment]
Thanks for testing!

> Your code aligns with the first character column, and gofmt aligns with the beginning /

gofmt "allows" either - I thought this looked better. If you move it back a space, go-mode will use that indent for further lines.

> electric-indent-mode only triggers indentation when the comment in that line begins at column 0

I did that intentionally so go-mode basically only indents on newline. The gofmt behavior is pretty arbitrary, so in general I wanted to leave the indent alone and let gofmt or the user tweak as they like.

**Comment by Murgalha** [comment]
> If you move it back a space, go-mode will use that indent for further lines.
That is so clever! Thank you so much for the changes.
