### ISSUE TITLE
no go-mode on melpa today?

### ISSUE THREAD

**Issue by uselessdetails** [dominikh/go-mode.el#372]
I'm not finding it although I know it was there a few weeks ago when I last downloaded it.

**Comment by psanford** [comment]
It looks like its still there: https://melpa.org/#/go-mode https://github.com/melpa/melpa/blob/master/recipes/go-mode

Maybe try `M-x package-refresh-contents`?

**Comment by uselessdetails** [comment]
Failed to download ‘melpa’ archive.

Hm.  Ok, maybe not a go-mode problem.
