### ISSUE TITLE
go mode does not work when open a single go file to edit

### ISSUE THREAD

**Issue by shizhz** [dominikh/go-mode.el#376]
Hi,

Is it possible to make go-mode work for a single go file or buffer which is outside any project? Currently I'll get the following error message:

> LSP :: test.go not in project or it is blacklisted.
> Suspicious state from syntax checker golangci-lint: Flycheck checker golangci-lint returned 5, but its output contained no errors: level=error msg="Running error: context loading failed: no go files to analyze"
> 
> Try installing a more recent version of golangci-lint, and please open a bug report if the issue persists in the latest release.  Thanks!

Thanks.

**Comment by psanford** [comment]
Those errors appear to be from lsp-mode and something that has hooked up golangci-lint to Flycheck. 

Those are not part of the go-mode package. go-mode works fine on single files.

**Comment by shizhz** [comment]
Yes it's not an issue of go-mode, it's the limitation of LS which needs a workspace to work correctly. I've asked help from ls-mode community and the workaround could be:

- For single file: add the directory to variable lsp-go-library-directories, then it will use the existing gopls connection if any
- For golang source block in org file, refer to https://github.com/yyoncho/lsp-mode/blob/SystemCrafters/docs/manual-language-docs/lsp-org.md 

The key is that you need to mock a workspace environment to make gopls happy. Hope this could help those who has the same problem as me.
