### ISSUE TITLE
Can't install package from Melpa

### ISSUE THREAD

**Issue by lackhoa** [dominikh/go-mode.el#378]
It gives this error:
```
Contacting host: melpa.org:80
package--with-response-buffer-1: http://melpa.org/packages/go-mode-20200822.1936.el: Not found
```

**Comment by psanford** [comment]
That looks like an issue with melpa, not go-mode.

The version you are trying to fetch is a few months old. Maybe try `M-x package-refresh-contents` to fetch new metadata.

If you are still having issues, the melpa project will be better able to assist you than we will.
