### ISSUE TITLE
Does not align closing parenthesis

### ISSUE THREAD

**Issue by ChoppinBlockParty** [dominikh/go-mode.el#379]
Not sure if it is this plugin responsibility or some generic emacs configuration. 
```
if myvar {
	} 
```
Expect the closing parenthesis to be on the same indentation level as `if`. It works find for other languages I work with, e.g. C++, javascript.

**Comment by psanford** [comment]
This should work fine. What version of emacs are you using?

Can you try a minimal emacs config file where you only load go-mode and see if that works?

**Comment by psanford** [comment]
Are other things indenting correctly or is nothing getting the proper indentation level?

**Comment by ChoppinBlockParty** [comment]
I found out it is due to `newline-and-indent`. I bound `ret` to it, works in most major modes. I think it should be possible to disable auto indentation in the mode, because most major modes do not indent on return?

**Comment by muirdm** [comment]
Instead of `newline-and-indent`, maybe turn on `electric-indent-mode`? Even if you keep using `newline-and-indent`, `electric-indent-mode` may still resolve the problem.

**Comment by ChoppinBlockParty** [comment]
I actually have `electric-indent-mode`. Still experience the problem.

**Comment by muirdm** [comment]
Can you create a minimal Emacs config that reproduces the issue?

**Comment by dominikh** [comment]
This issue has stalled. I'll reopen it if the asked-for information is provided.
