### ISSUE TITLE
Add optional support for tree-sitter

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-mode.el#396]
We can replace most, if not all, of our custom movement functions with tree-sitter, making them more robust.

**Comment by edkolev** [comment]
Is it viable to contribute `go-ts-mode` to emacs itself? With `eglot` already part of emacs, emacs will be able to provide modern Go environment out of the box, provided `gopls` is available.

**Comment by dominikh** [comment]
If you want to put up with GNU and the FSF to get your code into Emacs, feel free to. I, however, won't take part in that.

(I think there are also less political arguments against having go-ts-mode in Emacs, such as mismatching release cycles between Go and Emacs.)

**Comment by dominikh** [comment]
Based on the document To1ne linked to, it seems like we should implement a new major mode `go-ts-mode`. Code that can be shared between the current `go-mode` and the new `go-ts-mode` will go in a base mode `go-base-mode`.

I will probably work on this myself in the near future.

**Comment by zwpaper** [comment]
FYI

Emacs has worked on a go-ts-mode, https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=fee2efe1b035d601ac53a32801227402e9be8bca

**Comment by To1ne** [comment]
> Emacs has worked on a go-ts-mode, https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=fee2efe1b035d601ac53a32801227402e9be8bca

That's great! With that I consider this issue closed.

One thing would be nice though, if I could use `gofmt-before-save` with `go-ts-mode`. Something along the lines of:

```diff
 (defun gofmt-before-save ()
   "Add this to .emacs to run gofmt on the current buffer when saving:
 \(add-hook 'before-save-hook 'gofmt-before-save).

 Note that this will cause ‘go-mode’ to get loaded the first time
 you save any file, kind of defeating the point of autoloading."

   (interactive)
-   (when (eq major-mode 'go-mode) (gofmt)))
+   (when (member major-mode '(go-mode go-ts-mode)) (gofmt)))
```

Until that, I have this in my config:

```elisp
(defun my-go-mode-setup ()
  "Setup Go mode to my liking."
  (add-hook 'before-save-hook 'gofmt nil t))

(use-package go-mode
  :ensure t
  :mode (("\\.go$" . go-ts-mode))
  :hook ((go-mode go-ts-mode) . my-go-mode-setup)
  :custom (gofmt-command "goimports"))
```

Or you could use this if you like: https://gist.github.com/GnaneshKunal/3d3f982ce1903990eedd586952893422

**Comment by dominikh** [comment]
> That's great! With that I consider this issue closed.

I don't. Using that mode loses you most of the features of the current go-mode, and doesn't use tree-sitter to its full potential to replace most of the custom navigation functions in go-mode, like go-goto-arguments.

Big fan of the fact they took the name go-ts-mode, too, while not owning go-mode.

**Comment by dominikh** [comment]
Closing in favour of #428.
