### ISSUE TITLE
Please tag a new stable release if the master branch is in a good state

### ISSUE THREAD

**Issue by sten0** [dominikh/go-mode.el#406]
Hi,

I noticed that there have been 100 commits or so since the last tagged release (v1.5.0).  Would you please tag a new stable release if the master branch is in a good state?

Thanks!

**Comment by dominikh** [comment]
We bumped the version in 3273fcece5d9ab7edd4f15b2d6bce61f4e5a0666 but unfortunately forgot to push the new tag. I've just pushed it.

**Comment by sten0** [comment]
> We bumped the version in 3273fcece5d9ab7edd4f15b2d6bce61f4e5a0666 but unfortunately forgot to push the new tag. I've just pushed it.
>

Ah, it happens!  Thank you for the tagged released--much appreciated.
