### ISSUE TITLE
Emacs 29 (earlier too?) shows warning when entering go-mode

### ISSUE THREAD

**Issue by the42** [dominikh/go-mode.el#411]
in **messages**

    .emacs.d/elpa/go-mode-20220727.115/go-mode.el: Warning: Case 'fail will match ‘quote’.  If that’s intended, write (fail quote) instead.  Otherwise, don’t quote ‘fail’.

and more messages like that, none fatal though, just not 'pleasant to the eye'

**Comment by dominikh** [comment]
I couldn't reproduce the appearance of these messages in `*Messages*`. Can you confirm that c8525e627d2ddef8e13e4e25403cbc6b3a819c07 solves the issue for you?

**Comment by the42** [comment]
Fix confirmed
