### ISSUE TITLE
When using go-mode eglot failes to properly connect with gopls

### ISSUE THREAD

**Issue by the42** [dominikh/go-mode.el#413]
Using emacs 29 on windows from https://github.com/kiennq/emacs-build/releases/tag/v29.169.20221201.4a23421

When using go-mode eglot failes to properly connect with gopls

The actual error message I get is 

    Error in menu-bar-update-hook (imenu-update-menubar): (jsonrpc-error "request id=2 failed:" (jsonrpc-error-message . "Timed out")

I already commented out imenu-integration of go-mode, that's not the problem.

* If I uninstall go-mode and open the file, eglot correctly starts gopls
* If I literally open a go file and start eglot afterwards, gopls correctly loads.

The problem is rather hard to debug. In my particular project, out of 20? times gopls and eglot start to interact properly
If I open a very small project (so that gopls has probably not much to analyse) go-mode, eglot and gopls always work.

Maybe it is a problem with windows pre-maturely reporting back successful process spawning, maybe it is gopls pre-maturely returning control to the os while rpc thread is still blocked? It seems a rather interacted timing issue of which go-mode may actually not be the culprit but rather a promoter.

Reporting here nonetheless as without go-mode eglot and gopls work.

**Comment by dominikh** [comment]
Possibly related: https://github.com/joaotavora/eglot/issues/587 and https://github.com/golang/go/issues/54559

**Comment by the42** [comment]
Indeed, the fix is to use Emacs 30 OR install jsonrp.el https://elpa.gnu.org/packages/jsonrpc.html

Unrelated to go-mode
