### ISSUE TITLE
MELPA installation

### ISSUE THREAD

**Issue by xylifyx** [dominikh/go-mode.el#67]
I don't think the MELPA go-mode installation description is complete. Should I add something to my init files in addition to adding the repositories?

**Comment by dominikh** [comment]
The install instructions for MELPA link to http://melpa.org/#/getting-started and that document seems complete enough. We won't explain how to use ELPA itself.

**Comment by xylifyx** [comment]
The MELPA and ELPA documentation I could find, didn't say how to install a package only how to update them. It is described in the emacs help system but not very prominently. A little hint for people who are not emacs wizards and familiar with the package system would be nice, especially because it is the recommended way of installing go-mode.

**Comment by dominikh** [comment]
It shouldn't be expected from every package for Emacs to explain how the package manager, a core component of Emacs 24, works. 

The second result for "emacs elpa" on Google is http://ergoemacs.org/emacs/emacs_package_system.html which provides a detailed explanation on how to use it. 

In fact, our readme links to http://www.emacswiki.org/emacs/ELPA which indirectly explains how to install packages if one actually searches for "install" on that website. Admittedly, I think that wiki entry is horrible, and it used to be better, but that's something the emacswiki has to fix.

There's nothing to do here for us; maybe Emacs has to improve their documentation, but go-mode is a package for Emacs users, it shouldn't have to teach how to use Emacs first.

**Comment by xylifyx** [comment]
I fully agree that shouldn't be necessary. 

The link to  http://ergoemacs.org/emacs/emacs_package_system.html would have provided the needed information to me and probably most other Emacs users with no knowledge of the package system. I recon a link would be a helpful addition to the go-mode readme file.

If you look at http://www.emacswiki.org/emacs/Comments_on_ELPA you will see I am not the only one who couldn't find out how to find out how to install packages.

**Comment by dominikh** [comment]
I added a link to that guide in 59d1e827147bca990c500b783f27bda1ad2873ae

**Comment by c0ze** [comment]
Hello guys,
I'm trying to install via ELPA. I fetch the list with `list-packages` but I can not find `go-mode` there. Am I doing something wrong ?
