### ISSUE TITLE
Ignore already imported packages for go-import-add

### ISSUE THREAD

**Issue by thomasf** [dominikh/go-mode.el#70]
Is there a reason why it adds duplicates in the current implementation?

I want to use this for elisp snippet insertion code that adds (possibly) unused imports.

Sorry, but have not taken the time to study the current implementation yet.

**Comment by dominikh** [comment]
The reason it adds duplicates is because we don't check for duplicates. This was originally tracked as issue #27, which I closed when gofmt added a feature to delete duplicated imports. Most people use gofmt either manually or in their save hook, so there's little reason for us to do the work.

**Comment by thomasf** [comment]
Hi, thanks for a quick reply. 

I suspect that I might be better off writing the precondition check in go instead of adding even more regexps to elisp code. 

However, if I decide to implement it myself I'll do an pull request. 

Closing this for now.
