### ISSUE TITLE
Can we add a confirmation step to play integration?

### ISSUE THREAD

**Issue by javjar** [dominikh/go-mode.el#73]
`go-play-buffer` and `go-play-region` send code to the Playground, can we have a confirmation step before sending code to avoid accidentally sending it? :)
And maybe a setting variable if you want to avoid the confirmation step?

**Comment by dominikh** [comment]
Sorry, but that's not a feature we're going to add. Accidentally calling an Emacs function that sends code to a pastebin (such as the playground) isn't a common issue. If it's an issue for you, you will have to write your own code for this, either by writing wrapper functions that do ask for confirmation, or by advising (https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) `go-play-region`.
