### ISSUE TITLE
Problem with multiple workspaces (Godep)

### ISSUE THREAD

**Issue by artemave** [dominikh/go-mode.el#80]
I am using [spacemacs](https://github.com/syl20bnr/spacemacs) (develop branch). The go integration that comes with it mostly delegates to go-mode.el.

I am also using `godep`, so my `$GOPATH` looks like this: ![](http://cl.ly/image/0i3R3u1o0k3b/Image%202015-02-28%20at%201.14.31%20pm.png)

Now, if I try to `gorename` from emacs, I get ![](http://cl.ly/image/403o1h30260Q/Image%202015-02-28%20at%201.02.37%20pm.png)

It can not find `negroni` package because is installed in godeps workspace.

But if I do the same from the command line, it works: ![](http://cl.ly/image/0b3g0e0x031y/Image%202015-02-28%20at%201.05.11%20pm.png)

In emacs, evaluating `(getenv "GOPATH")` produces the correct path: ![](http://cl.ly/image/2o0p2g2p2y18/Image%202015-02-28%20at%201.07.15%20pm.png)

So what it is wrong? Is it me? Or is it a bug? I tried to look at your code, but I am a complete emacs/lisp n00b, so didn't get far :)

Thanks!

**Comment by dominikh** [comment]
`gorename` isn't part of go-mode, it's in a third party package (the one that comes with the gorename utility), so please file this bug with them instead, thanks.

**Comment by artemave** [comment]
gorename is not the problem here (go oracle breaks in exactly the same manner). As you can see here ![](http://cl.ly/image/403o1h30260Q/Image%202015-02-28%20at%201.02.37%20pm.png)

The problem is that `$GOPATH` is not being expanded (I guess)

**Comment by dominikh** [comment]
And the oracle is also not part of go-mode, and written by exactly the same author as gorename. 

```
(progn
  (setenv "GOPATH" "a:b:c")
  (go-root-and-paths))
;; ("/usr/lib/go" "a" "b" "c")
```

```
$ GOPATH=/tmp/junk1 go get github.com/justinas/alice
$ GOPATH=/tmp/junk2 go get github.com/justinas/nosurf
```

```
(remove-if-not (lambda (x) (and x (go--string-prefix-p "github" x)))
               (progn
                 (setenv "GOPATH" "/tmp/junk1:/tmp/junk2")
                 (go-packages)))
;; ("github.com/justinas/alice" "github.com/justinas/nosurf")
```

go-mode knows how to work with multiple GOPATH entries. Please file bugs with gorename and the oracle respectively.

**Comment by dominikh** [comment]
Additionally, I cannot reproduce the problem to begin with. `gorename` is working just fine here with multiple GOPATH entries. Please verify that the issue also happens with a normal GNU Emacs and an untampered copy of go-mode as well as gorename.

**Comment by artemave** [comment]
Thank you for this investigation. Like I said, I am very new to emacs, so I misjudged where the problem comes from.

One last question though, when you say "untampered copy of go-mode" what exactly does that mean? Because I am under impression that it is elpa package I am using. I can see it in `~/.emacs.d/elpa/go-mode-20150226.1606`

**Comment by dominikh** [comment]
Maybe, I'm not familiar with spacemacs. It does bundle a copy of gorename, no idea about oracle or the actual go-mode. Either way you should test with a clean GNU Emacs without any custom configuration to make sure the problem isn't with anything that spacemacs is doing.

**Comment by artemave** [comment]
I'll do that, thank you.

**Comment by artemave** [comment]
To follow up on this, I got down to the root of the problem: I am using [direnv](https://github.com/zimbatm/direnv) with Godeps and direnv is using directory hooks that don't get picked when go-mode shells out to `go env GOROOT GOPATH`

I could not figure out how to get around this, so I forked go-mode and changed the way GOPATH is read: https://github.com/artemave/go-mode.el/commit/7040cf8e7b9a9958dd3d0ed8fc6bf3e8182b4a89

I am happy to open a pr if you think this change is useful.

**Comment by dominikh** [comment]
I'd prefer if the interaction with direnv got fixed instead. If `(getenv "GOPATH")` works, I can't see why `go env GOPATH` wouldn't.

**Comment by artemave** [comment]
Fair enough.

> If `(getenv "GOPATH")` works, I can't see why `go env GOPATH` wouldn't.

I am guessing the difference is that the latter is run in a subshell, whereas `(getenv "GOPATH")` is not.

**Comment by dominikh** [comment]
> that the latter is run in a subshell

And the nature of environment variables is that subprocesses inherit the variables of the parent process.

**Comment by artemave** [comment]
That is my understanding too. Yet, evaling `(getenv "GOPATH")` gives result different to `M-! go env GOPATH`

I tried suggestions from [this link](http://emacs.stackexchange.com/questions/2573/how-to-make-shell-command-run-using-shell-profile-and-current-directory-hooks-e) (the only relevant I managed to find) but to no luck.
