### ISSUE TITLE
teach godef-jump about traversing imports

### ISSUE THREAD

**Issue by jmhodges** [dominikh/go-mode.el#84]
This is probably Hard™ but it would be nice if godef-jump could jump to a symbol that was defined in another package. I didn't see an issue for this already, but maybe I looked for the wrong keywords.

My 10 minutes of thinking has one not great implementation. If godef doesn't find a definition for a symbol, but the symbol has a period and a name before that prepended, it could somehow get the imports list (an AST tool, or, for a quick-and-dirty implementation with a regex or two), and match the name before the period with the symbol. With the import matched, then go-mode would walk the values of GOPATH for the path that contains the import directory and run godef again in that directory.

I'm sure there is a better version of this implementation that could be done with an oracle-like tool but my thought experiment was limited to what's being used in go-mode today.

**Comment by dominikh** [comment]
Sorry, but I'm not really following. Both godef-jump and godef-describe already work across package boundaries, as can be seen for example in http://dominik.honnef.co/video/go_emacs/godef_mp4.mp4 – am I missing something here?

**Comment by jmhodges** [comment]
Okay, let me give an example of what is failing for me. If I use godef-jump on the word "String" here, it fails with "godef: no declaration found for aws.String":

    import (
	    "fmt"

	    "github.com/awslabs/aws-sdk-go/aws"
    )

    func main() {
	    foobar := aws.String("foobar")
	    fmt.Printf(*foobar)
    }

**Comment by dominikh** [comment]
Please run `(getenv "GOPATH")` (e.g. via `M-:`) and confirm that the value is what you'd expect. This is likely an error in configuration.

**Comment by jmhodges** [comment]
Argh. Somehow Emacs has my crazy full .bash_profile PATH correctly, but GOPATH is nil.

**Comment by jmhodges** [comment]
For future people: this was the usual MacOS-is-weird. Be sure to call `(exec-path-from-shell-copy-env "GOPATH")` in your initialization. That function can be found here: https://github.com/purcell/exec-path-from-shell
