### ISSUE TITLE
Use `go doc` for godoc-at-point

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-mode.el#86]

**Comment by stardiviner** [comment]
+1

**Comment by dominikh** [comment]
Issues without description are confusing… See https://github.com/dominikh/go-mode.el/pull/100#issuecomment-139833298 for what my original thought process was, and how it's not as easy as I thought.

**Comment by kostya-sh** [comment]
After introduction of `godoc-command`, `godoc-at-point` doesn't work when `godoc-command` is "go doc":

```
go doc /home/user/go/src/testing/ Next
godoc: doc: import "/home/user/go/src/testing/": cannot import absolute path
```

Probably godoc should always be used in godoc-at-point for now.
