### ISSUE TITLE
godef-jump do not work if emacs was not run in terminal

### ISSUE THREAD

**Issue by deterok** [dominikh/go-mode.el#89]
```
Could not run godef binary
```

``` sh
whereis godef
godef: /home/deterok/.local/lib/go/bin/godef
```

**Comment by deterok** [comment]
It's work if i have added this in init.el
```elisp
(setenv "GOPATH" (concat (file-truename "~/") ".local/lib/go/"))
(setenv "PATH"
        (concat (getenv "PATH") ":" (concat (getenv "GOPATH") "bin")))
(set-default 'godef-command (concat (getenv "GOPATH") "bin/godef"))
```

**Comment by dominikh** [comment]
This is an issue with your environment. Your shell and your GUI session have different environment variables. 

If you're using OS X, look into exec-path (see http://emacs.stackexchange.com/a/553 for example).

If you're using a different platform, ensure that your X session has the correct PATH set.
