### ISSUE TITLE
Syntax highlighting of function declarations is inconsistent.

### ISSUE THREAD

**Issue by adamfaulkner** [dominikh/go-mode.el#90]
![emacs syntax highlighting bug](https://cloud.githubusercontent.com/assets/1405916/8602332/a7bc582e-2626-11e5-8430-fd10f85654f4.png)

Hello.

I occasionally encounter bugs with go-mode's syntax highlighting of function declarations. 

I can cause this to happen by first typing the following:

```
func broken(
    arg1 string,
    arg2 string) {
}
```

After typing it, if I insert a new line above the `func broken(`, the syntax highlighting of the `func` keyword disappears (see screenshot). 

Any ideas? Thanks!

**Comment by dominikh** [comment]
8baa836 stops fontification from breaking outright. 

This doesn't change the fact that fontification of function declarations doesn't really support multi-line declarations right now, which means that sometimes the types get highlighted, sometimes they don't, and it might flicker back and forth.

Multi-line fontification in Emacs is usually a huge pain, but I'll see what can be done about it.

**Comment by adamfaulkner** [comment]
I found today that if I manually run `(jit-lock-mode nil)` in a go buffer, it prevents the problem from happening. Not sure that's helpful, I'll keep digging.

**Comment by dominikh** [comment]
It'll probably just fail in other ways now. Also, you don't want to disable jit-lock-mode; for large buffers that'll have quite the negative performance impact.

**Comment by psanford** [comment]
Function arguments split across lines should fontify properly as of c020e2cba0f9684cc060cbbdc492d9a470420bf4.
