### ISSUE TITLE
Describe type of a field/variable in godef-describe output

### ISSUE THREAD

**Issue by kostya-sh** [dominikh/go-mode.el#94]
I want to propose a new feature for godef-describe that I think will make it more useful.

When showing a field or variable definition of one of the following kinds:

- struct
- interface
- array of structs or interfaces
- array of pointers to struct or interface
- pointer to any of the above

godef-describe will also show the definition of the struct or interface.

Something like (for `var v *[]*MyStruct` for example):

    v *[]*MyStruct

    type MyStruct = struct {
        ...
    }

**Comment by dominikh** [comment]
This should probably be a request for godef itself (github.com/rogpeppe/godef), not go-mode. If godef isn't outputting that information, we can't display it.

**Comment by kostya-sh** [comment]
godef already supports this via `-A` flag

**Comment by dominikh** [comment]
The `-A` flag really isn't comparable to what you're requesting. It only really works for variables that are structs. For those, it displays the fields (in some custom format, not standard Go syntax). For any other variable, it will not show any type information. You can easily test that with the example you provided.

As such, `-A` isn't all that useful to us.

**Comment by kostya-sh** [comment]
`-A` indeed works only for variables and doesn't work for fields. The output is not using Go syntax so it should be transformed to something more readable by godef-describe before showing it. Something like:

    Fields:
      a int
      b string
    Methods:
      func f1(...)...
      func f2(...)...

Possibly restricting length of method list.

I will try to implement something along these lines when I have time though I am not very familiar with emacs yet, so it might take a while.

**Comment by kostya-sh** [comment]
I am going to close this issue as `go-guru-describe` already provides the requested functionality.
