### ISSUE TITLE
Wishlist: jump to an identifier given as string

### ISSUE THREAD

**Issue by tv42** [dominikh/go-mode.el#99]
I'd like jump to an identifier in the style of `go doc github.com/tv42/base58.DecodeToBig`, inputting that kind of a string to be parsed. I tried to write it myself, but I realized I don't actually know of a convenient way to  get that information. Do you happen to know of a way?

Ulterior motive: I want to hook this up to `org-add-link-type` and make slightly more robust & cleaner links in my org-mode.

**Comment by dominikh** [comment]
I don't think there's currently a tool out there that provides this feature. You could get very creative and parse the output of `godoc -html github.com/tv42/base58 DecodeToBig`, but that is unlikely to make you happy.

You could try to hack something together by generating Go code and running godef on it, though:

```
#!/bin/bash
import=${1%.*}
identifier=${1##*.}
code="package main; import xxx \"$import\"; var _ = xxx.$identifier"
godef -i -o $((${#code}-1)) <<<"$code"
```

```
$ go-find github.com/tv42/base58.DecodeToBig
/home/dominikh/prj/go/src/github.com/tv42/base58/base58.go:34:6
```

**Comment by tv42** [comment]
That's a good idea, though the split rule isn't as clear (`os.File.Read`, `github.com/foo.bar/baz.quux/x.y.z.Abc`; and core docs saying `(*os.File).Read`, but that leaves you guessing what the real import path is). In https://github.com/tv42/jog I went for the godoc.org-style `#` separator, for that reason, e.g. `import.path.here#TypeName.MethodName`. That seems doable. Thanks for the idea, I think I'll write something based on this.

**Comment by tv42** [comment]
The godef trick naturally fails on unexported identifiers.

**Comment by dominikh** [comment]
> The godef trick naturally fails on unexported identifiers

Sort of. It works fine with package-level unexported identifiers. It doesn't seem to work with unexported identifiers that are methods, fields etc.

**Comment by tv42** [comment]
Well, this now lives at https://github.com/tv42/where and doesn't really seem to intersect with go-mode much, so I guess we're done here. Thanks for the ideas!
